// ============================================
// YouTube Transcript & Bilingual Service
// ============================================

export interface TranscriptCue {
  id: number
  start: number // in seconds
  duration: number // in seconds
  end: number // in seconds
  textEn: string
  textVi: string
  words: string[]
}

export interface VideoInfo {
  videoId: string
  title: string
  channel: string
  thumbnailUrl: string
  durationFormatted?: string
}

// Curated English Learning Videos with Full Accurate Speech Transcripts
export const CURATED_LEARNING_VIDEOS: { info: VideoInfo; sampleCues: TranscriptCue[] }[] = [
  {
    info: {
      videoId: 'UF8uR6Z6KLc',
      title: 'Steve Jobs 2005 Stanford Commencement Address',
      channel: 'Stanford University',
      thumbnailUrl: 'https://img.youtube.com/vi/UF8uR6Z6KLc/hqdefault.jpg',
      durationFormatted: '15:04',
    },
    sampleCues: [
      {
        id: 1,
        start: 0.0,
        duration: 33.5,
        end: 33.5,
        textEn: '[Applause & Commencement Gathering]',
        textVi: '[Khai m\u1ea1c & Ti\u1ebfng v\u1ed7 tay ch\u00e0o m\u1eebng]',
        words: ['[Applause', '&', 'Commencement', 'Gathering]'],
      },
      {
        id: 2,
        start: 34.0,
        duration: 12.0,
        end: 46.0,
        textEn:
          'Thank you. I am honored to be with you today at your commencement from one of the finest universities in the world.',
        textVi:
          'C\u1ea3m \u01a1n c\u00e1c b\u1ea1n. T\u00f4i r\u1ea5t vinh h\u1ea1nh \u0111\u01b0\u1ee3c c\u00f3 m\u1eb7t c\u00f9ng c\u00e1c b\u1ea1n h\u00f4m nay t\u1ea1i l\u1ec5 t\u1ed1t nghi\u1ec7p t\u1eeb m\u1ed9t trong nh\u1eefng tr\u01b0\u1eddng \u0111\u1ea1i h\u1ecdc danh gi\u00e1 nh\u1ea5t th\u1ebf gi\u1edbi.',
        words: [
          'Thank',
          'you.',
          'I',
          'am',
          'honored',
          'to',
          'be',
          'with',
          'you',
          'today',
          'at',
          'your',
          'commencement',
          'from',
          'one',
          'of',
          'the',
          'finest',
          'universities',
          'in',
          'the',
          'world.',
        ],
      },
      {
        id: 3,
        start: 46.5,
        duration: 5.5,
        end: 52.0,
        textEn: 'Truth be told, I never graduated from college.',
        textVi:
          'N\u00f3i th\u1eadt l\u00f2ng, t\u00f4i ch\u01b0a t\u1eebng t\u1ed1t nghi\u1ec7p \u0111\u1ea1i h\u1ecdc.',
        words: ['Truth', 'be', 'told,', 'I', 'never', 'graduated', 'from', 'college.'],
      },
      {
        id: 4,
        start: 52.5,
        duration: 6.5,
        end: 59.0,
        textEn: 'And this is the closest I have ever gotten to a college graduation.',
        textVi:
          'V\u00e0 \u0111\u00e2y l\u00e0 l\u1ea7n t\u00f4i ti\u1ebfn g\u1ea7n nh\u1ea5t t\u1edbi m\u1ed9t bu\u1ed5i l\u1ec5 t\u1ed1t nghi\u1ec7p \u0111\u1ea1i h\u1ecdc.',
        words: [
          'And',
          'this',
          'is',
          'the',
          'closest',
          'I',
          'have',
          'ever',
          'gotten',
          'to',
          'a',
          'college',
          'graduation.',
        ],
      },
      {
        id: 5,
        start: 59.5,
        duration: 7.0,
        end: 66.5,
        textEn:
          "Today I want to tell you three stories from my life. That's it. No big deal. Just three stories.",
        textVi:
          'H\u00f4m nay t\u00f4i mu\u1ed1n k\u1ec3 cho c\u00e1c b\u1ea1n nghe ba c\u00e2u chuy\u1ec7n trong cu\u1ed9c \u0111\u1eddi t\u00f4i. Ch\u1ec9 v\u1eady th\u00f4i. Kh\u00f4ng c\u00f3 g\u00ec to t\u00e1t c\u1ea3. Ch\u1ec9 l\u00e0 ba c\u00e2u chuy\u1ec7n.',
        words: [
          'Today',
          'I',
          'want',
          'to',
          'tell',
          'you',
          'three',
          'stories',
          'from',
          'my',
          'life.',
          "That's",
          'it.',
          'No',
          'big',
          'deal.',
          'Just',
          'three',
          'stories.',
        ],
      },
      {
        id: 6,
        start: 67.0,
        duration: 8.5,
        end: 75.5,
        textEn: 'The first story is about connecting the dots.',
        textVi:
          'C\u00e2u chuy\u1ec7n \u0111\u1ea7u ti\u00ean l\u00e0 v\u1ec1 vi\u1ec7c k\u1ebft n\u1ed1i nh\u1eefng d\u1ea5u ch\u1ea5m.',
        words: ['The', 'first', 'story', 'is', 'about', 'connecting', 'the', 'dots.'],
      },
      {
        id: 7,
        start: 76.0,
        duration: 11.5,
        end: 87.5,
        textEn:
          'I dropped out of Reed College after the first 6 months, but then stayed around as a drop-in for another 18 months or so before I really quit.',
        textVi:
          'T\u00f4i \u0111\u00e3 b\u1ecf h\u1ecdc t\u1ea1i tr\u01b0\u1eddng Cao \u0111\u1eb3ng Reed sau 6 th\u00e1ng \u0111\u1ea7u, nh\u01b0ng sau \u0111\u00f3 v\u1eabn \u1edf l\u1ea1i h\u1ecdc d\u1ef1 th\u00ednh th\u00eam kho\u1ea3ng 18 th\u00e1ng tr\u01b0\u1edbc khi th\u1ef1c s\u1ef1 ngh\u1ec9 h\u1eb3n.',
        words: [
          'I',
          'dropped',
          'out',
          'of',
          'Reed',
          'College',
          'after',
          'the',
          'first',
          '6',
          'months,',
          'but',
          'then',
          'stayed',
          'around',
          'as',
          'a',
          'drop-in',
          'for',
          'another',
          '18',
          'months',
          'or',
          'so',
          'before',
          'I',
          'really',
          'quit.',
        ],
      },
      {
        id: 8,
        start: 88.0,
        duration: 4.0,
        end: 92.0,
        textEn: 'So why did I drop out?',
        textVi: 'V\u1eady t\u1ea1i sao t\u00f4i l\u1ea1i b\u1ecf h\u1ecdc?',
        words: ['So', 'why', 'did', 'I', 'drop', 'out?'],
      },
      {
        id: 9,
        start: 92.5,
        duration: 9.0,
        end: 101.5,
        textEn:
          'It started before I was born. My biological mother was a young, unwed college graduate student, and she decided to put me up for adoption.',
        textVi:
          'Chuy\u1ec7n b\u1eaft \u0111\u1ea7u t\u1eeb tr\u01b0\u1edbc khi t\u00f4i sinh ra. M\u1eb9 ru\u1ed9t t\u00f4i l\u00e0 m\u1ed9t n\u1eef sinh vi\u00ean t\u1ed1t nghi\u1ec7p \u0111\u1ea1i h\u1ecdc tr\u1ebb ch\u01b0a k\u1ebft h\u00f4n, v\u00e0 b\u00e0 quy\u1ebft \u0111\u1ecbnh cho t\u00f4i l\u00e0m con nu\u00f4i.',
        words: [
          'It',
          'started',
          'before',
          'I',
          'was',
          'born.',
          'My',
          'biological',
          'mother',
          'was',
          'a',
          'young,',
          'unwed',
          'college',
          'graduate',
          'student,',
          'and',
          'she',
          'decided',
          'to',
          'put',
          'me',
          'up',
          'for',
          'adoption.',
        ],
      },
      {
        id: 10,
        start: 102.0,
        duration: 9.0,
        end: 111.0,
        textEn:
          'She felt very strongly that I should be adopted by college graduates, so everything was all set for me to be adopted at birth by a lawyer and his wife.',
        textVi:
          'B\u00e0 tha thi\u1ebft mong mu\u1ed1n t\u00f4i \u0111\u01b0\u1ee3c nh\u1eadn nu\u00f4i b\u1edfi nh\u1eefng ng\u01b0\u1eddi \u0111\u00e3 t\u1ed1t nghi\u1ec7p \u0111\u1ea1i h\u1ecdc, n\u00ean m\u1ecdi th\u1ee9 \u0111\u00e3 \u0111\u01b0\u1ee3c thu x\u1ebfp \u0111\u1ec3 t\u00f4i \u0111\u01b0\u1ee3c m\u1ed9t lu\u1eadt s\u01b0 v\u00e0 v\u1ee3 \u00f4ng \u1ea5y nh\u1eadn nu\u00f4i t\u1eeb l\u00fac l\u1ecdt l\u00f2ng.',
        words: [
          'She',
          'felt',
          'very',
          'strongly',
          'that',
          'I',
          'should',
          'be',
          'adopted',
          'by',
          'college',
          'graduates,',
          'so',
          'everything',
          'was',
          'all',
          'set',
          'for',
          'me',
          'to',
          'be',
          'adopted',
          'at',
          'birth',
          'by',
          'a',
          'lawyer',
          'and',
          'his',
          'wife.',
        ],
      },
      {
        id: 11,
        start: 111.5,
        duration: 8.0,
        end: 119.5,
        textEn:
          'Except that when I popped out they decided at the last minute that they really wanted a girl.',
        textVi:
          'Ngo\u1ea1i tr\u1eeb vi\u1ec7c khi t\u00f4i ch\u00e0o \u0111\u1eddi, v\u00e0o ph\u00fat ch\u00f3t h\u1ecd l\u1ea1i quy\u1ebft \u0111\u1ecbnh r\u1eb1ng h\u1ecd th\u1ef1c s\u1ef1 mu\u1ed1n m\u1ed9t b\u00e9 g\u00e1i.',
        words: [
          'Except',
          'that',
          'when',
          'I',
          'popped',
          'out',
          'they',
          'decided',
          'at',
          'the',
          'last',
          'minute',
          'that',
          'they',
          'really',
          'wanted',
          'a',
          'girl.',
        ],
      },
      {
        id: 12,
        start: 120.0,
        duration: 10.5,
        end: 130.5,
        textEn:
          "So my parents, who were on a waiting list, got a call in the middle of the night asking: 'We have an unexpected baby boy; do you want him?' They said: 'Of course.'",
        textVi:
          "V\u00ec v\u1eady, b\u1ed1 m\u1eb9 t\u00f4i \u0111ang \u1edf trong danh s\u00e1ch ch\u1edd \u0111\u00e3 nh\u1eadn \u0111\u01b0\u1ee3c cu\u1ed9c g\u1ecdi l\u00fac n\u1eeda \u0111\u00eam h\u1ecfi: 'Ch\u00fang t\u00f4i c\u00f3 m\u1ed9t b\u00e9 trai ngo\u00e0i d\u1ef1 ki\u1ebfn; \u00f4ng b\u00e0 c\u00f3 mu\u1ed1n nh\u1eadn kh\u00f4ng?' H\u1ecd \u0111\u00e1p: 'T\u1ea5t nhi\u00ean r\u1ed3i.'",
        words: [
          'So',
          'my',
          'parents,',
          'who',
          'were',
          'on',
          'a',
          'waiting',
          'list,',
          'got',
          'a',
          'call',
          'in',
          'the',
          'middle',
          'of',
          'the',
          'night',
          'asking:',
          "'We",
          'have',
          'an',
          'unexpected',
          'baby',
          'boy;',
          'do',
          'you',
          'want',
          "him?'",
          'They',
          'said:',
          "'Of",
          "course.'",
        ],
      },
      {
        id: 13,
        start: 131.0,
        duration: 11.5,
        end: 142.5,
        textEn:
          'My biological mother later found out that my mother had never graduated from college and that my father had never graduated from high school. She refused to sign the final adoption papers.',
        textVi:
          'M\u1eb9 ru\u1ed9t t\u00f4i sau \u0111\u00f3 ph\u00e1t hi\u1ec7n ra r\u1eb1ng m\u1eb9 nu\u00f4i t\u00f4i ch\u01b0a t\u1eebng h\u1ecdc \u0111\u1ea1i h\u1ecdc v\u00e0 b\u1ed1 nu\u00f4i t\u00f4i ch\u01b0a t\u1ed1t nghi\u1ec7p c\u1ea5p ba. B\u00e0 \u0111\u00e3 t\u1eeb ch\u1ed1i k\u00fd gi\u1ea5y t\u1edd nh\u1eadn nu\u00f4i cu\u1ed1i c\u00f9ng.',
        words: [
          'My',
          'biological',
          'mother',
          'later',
          'found',
          'out',
          'that',
          'my',
          'mother',
          'had',
          'never',
          'graduated',
          'from',
          'college',
          'and',
          'that',
          'my',
          'father',
          'had',
          'never',
          'graduated',
          'from',
          'high',
          'school.',
          'She',
          'refused',
          'to',
          'sign',
          'the',
          'final',
          'adoption',
          'papers.',
        ],
      },
      {
        id: 14,
        start: 143.0,
        duration: 9.5,
        end: 152.5,
        textEn:
          'She only relented a few months later when my parents promised that I would someday go to college.',
        textVi:
          'B\u00e0 ch\u1ec9 m\u1ee7i l\u00f2ng v\u00e0i th\u00e1ng sau \u0111\u00f3 khi b\u1ed1 m\u1eb9 t\u00f4i h\u1ee9a r\u1eb1ng m\u1ed9t ng\u00e0y n\u00e0o \u0111\u00f3 t\u00f4i s\u1ebd \u0111\u01b0\u1ee3c v\u00e0o \u0111\u1ea1i h\u1ecdc.',
        words: [
          'She',
          'only',
          'relented',
          'a',
          'few',
          'months',
          'later',
          'when',
          'my',
          'parents',
          'promised',
          'that',
          'I',
          'would',
          'someday',
          'go',
          'to',
          'college.',
        ],
      },
      {
        id: 15,
        start: 153.0,
        duration: 11.5,
        end: 164.5,
        textEn:
          "And 17 years later I did go to college. But I naively chose a college that was almost as expensive as Stanford, and all of my working-class parents' savings were being spent on my college tuition.",
        textVi:
          'V\u00e0 17 n\u0103m sau t\u00f4i \u0111\u00e3 th\u1ef1c s\u1ef1 \u0111i h\u1ecdc \u0111\u1ea1i h\u1ecdc. Nh\u01b0ng t\u00f4i \u0111\u00e3 ng\u00e2y th\u01a1 ch\u1ecdn m\u1ed9t tr\u01b0\u1eddng \u0111\u1eaft \u0111\u1ecf g\u1ea7n nh\u01b0 Stanford, v\u00e0 to\u00e0n b\u1ed9 ti\u1ec1n ti\u1ebft ki\u1ec7m c\u1ee7a b\u1ed1 m\u1eb9 thu\u1ed9c t\u1ea7ng l\u1edbp lao \u0111\u1ed9ng \u0111\u1ec1u b\u1ecb ti\u00eau s\u1ea1ch v\u00e0o h\u1ecdc ph\u00ed c\u1ee7a t\u00f4i.',
        words: [
          'And',
          '17',
          'years',
          'later',
          'I',
          'did',
          'go',
          'to',
          'college.',
          'But',
          'I',
          'naively',
          'chose',
          'a',
          'college',
          'that',
          'was',
          'almost',
          'as',
          'expensive',
          'as',
          'Stanford,',
          'and',
          'all',
          'of',
          'my',
          'working-class',
          "parents'",
          'savings',
          'were',
          'being',
          'spent',
          'on',
          'my',
          'college',
          'tuition.',
        ],
      },
      {
        id: 16,
        start: 165.0,
        duration: 10.5,
        end: 175.5,
        textEn:
          "After six months, I couldn't see the value in it. I had no idea what I wanted to do with my life and no idea how college was going to help me figure it out.",
        textVi:
          'Sau s\u00e1u th\u00e1ng, t\u00f4i kh\u00f4ng nh\u00ecn th\u1ea5y gi\u00e1 tr\u1ecb \u1edf \u0111\u00f3. T\u00f4i kh\u00f4ng bi\u1ebft m\u00ecnh mu\u1ed1n l\u00e0m g\u00ec v\u1edbi cu\u1ed9c \u0111\u1eddi m\u00ecnh v\u00e0 kh\u00f4ng bi\u1ebft tr\u01b0\u1eddng \u0111\u1ea1i h\u1ecdc s\u1ebd gi\u00fap t\u00f4i t\u00ecm ra \u0111i\u1ec1u \u0111\u00f3 b\u1eb1ng c\u00e1ch n\u00e0o.',
        words: [
          'After',
          'six',
          'months,',
          'I',
          "couldn't",
          'see',
          'the',
          'value',
          'in',
          'it.',
          'I',
          'had',
          'no',
          'idea',
          'what',
          'I',
          'wanted',
          'to',
          'do',
          'with',
          'my',
          'life',
          'and',
          'no',
          'idea',
          'how',
          'college',
          'was',
          'going',
          'to',
          'help',
          'me',
          'figure',
          'it',
          'out.',
        ],
      },
      {
        id: 17,
        start: 176.0,
        duration: 11.5,
        end: 187.5,
        textEn:
          'And here I was spending all of the money my parents had saved their entire life. So I decided to drop out and trust that it would all work out OK.',
        textVi:
          'V\u00e0 \u1edf \u0111\u00e2y t\u00f4i \u0111ang ti\u00eau h\u1ebft s\u1ed1 ti\u1ec1n b\u1ed1 m\u1eb9 d\u00e0nh d\u1ee5m c\u1ea3 \u0111\u1eddi. V\u00ec v\u1eady t\u00f4i quy\u1ebft \u0111\u1ecbnh b\u1ecf h\u1ecdc v\u00e0 tin t\u01b0\u1edfng r\u1eb1ng m\u1ecdi chuy\u1ec7n r\u1ed3i s\u1ebd \u1ed5n th\u1ecfa.',
        words: [
          'And',
          'here',
          'I',
          'was',
          'spending',
          'all',
          'of',
          'the',
          'money',
          'my',
          'parents',
          'had',
          'saved',
          'their',
          'entire',
          'life.',
          'So',
          'I',
          'decided',
          'to',
          'drop',
          'out',
          'and',
          'trust',
          'that',
          'it',
          'would',
          'all',
          'work',
          'out',
          'OK.',
        ],
      },
      {
        id: 18,
        start: 188.0,
        duration: 8.5,
        end: 196.5,
        textEn:
          'It was pretty scary at the time, but looking back it was one of the best decisions I ever made.',
        textVi:
          'L\u00fac \u0111\u00f3 th\u1eadt \u0111\u00e1ng s\u1ee3, nh\u01b0ng nh\u00ecn l\u1ea1i th\u00ec \u0111\u00f3 l\u00e0 m\u1ed9t trong nh\u1eefng quy\u1ebft \u0111\u1ecbnh s\u00e1ng su\u1ed1t nh\u1ea5t \u0111\u1eddi t\u00f4i.',
        words: [
          'It',
          'was',
          'pretty',
          'scary',
          'at',
          'the',
          'time,',
          'but',
          'looking',
          'back',
          'it',
          'was',
          'one',
          'of',
          'the',
          'best',
          'decisions',
          'I',
          'ever',
          'made.',
        ],
      },
      {
        id: 19,
        start: 197.0,
        duration: 10.5,
        end: 207.5,
        textEn:
          "The minute I dropped out I could stop taking the required classes that didn't interest me, and begin dropping in on the ones that looked interesting.",
        textVi:
          'Kho\u1ea3nh kh\u1eafc t\u00f4i b\u1ecf h\u1ecdc, t\u00f4i c\u00f3 th\u1ec3 d\u1eebng c\u00e1c m\u00f4n b\u1eaft bu\u1ed9c nh\u00e0m ch\u00e1n v\u00e0 b\u1eaft \u0111\u1ea7u d\u1ef1 th\u00ednh nh\u1eefng m\u00f4n h\u1ecdc tr\u00f4ng th\u00fa v\u1ecb.',
        words: [
          'The',
          'minute',
          'I',
          'dropped',
          'out',
          'I',
          'could',
          'stop',
          'taking',
          'the',
          'required',
          'classes',
          'that',
          "didn't",
          'interest',
          'me,',
          'and',
          'begin',
          'dropping',
          'in',
          'on',
          'the',
          'ones',
          'that',
          'looked',
          'interesting.',
        ],
      },
      {
        id: 20,
        start: 208.0,
        duration: 11.5,
        end: 219.5,
        textEn:
          "It wasn't all romantic. I didn't have a dorm room, so I slept on the floor in friends' rooms, I returned Coke bottles for the 5\u00a2 deposits to buy food with,",
        textVi:
          'M\u1ecdi th\u1ee9 kh\u00f4ng h\u1ec1 m\u00e0u h\u1ed3ng. T\u00f4i kh\u00f4ng c\u00f3 ph\u00f2ng k\u00fd t\u00fac x\u00e1 n\u00ean ph\u1ea3i ng\u1ee7 tr\u00ean s\u00e0n nh\u00e0 b\u1ea1n b\u00e8, \u0111\u1ed5i v\u1ecf chai Coca l\u1ea5y 5 xu mua \u0111\u1ed3 \u0103n,',
        words: [
          'It',
          "wasn't",
          'all',
          'romantic.',
          'I',
          "didn't",
          'have',
          'a',
          'dorm',
          'room,',
          'so',
          'I',
          'slept',
          'on',
          'the',
          'floor',
          'in',
          "friends'",
          'rooms,',
          'I',
          'returned',
          'Coke',
          'bottles',
          'for',
          'the',
          '5\u00a2',
          'deposits',
          'to',
          'buy',
          'food',
          'with,',
        ],
      },
      {
        id: 21,
        start: 220.0,
        duration: 11.5,
        end: 231.5,
        textEn:
          'and I would walk the 7 miles across town every Sunday night to get one good meal a week at the Hare Krishna temple. I loved it.',
        textVi:
          'v\u00e0 t\u00f4i th\u01b0\u1eddng \u0111i b\u1ed9 7 d\u1eb7m xuy\u00ean th\u00e0nh ph\u1ed1 m\u1ed7i t\u1ed1i Ch\u1ee7 nh\u1eadt \u0111\u1ec3 \u0103n b\u1eefa c\u01a1m ngon t\u1ea1i \u0111\u1ec1n Hare Krishna. T\u00f4i y\u00eau th\u00edch \u0111i\u1ec1u \u0111\u00f3.',
        words: [
          'and',
          'I',
          'would',
          'walk',
          'the',
          '7',
          'miles',
          'across',
          'town',
          'every',
          'Sunday',
          'night',
          'to',
          'get',
          'one',
          'good',
          'meal',
          'a',
          'week',
          'at',
          'the',
          'Hare',
          'Krishna',
          'temple.',
          'I',
          'loved',
          'it.',
        ],
      },
      {
        id: 22,
        start: 232.0,
        duration: 11.5,
        end: 243.5,
        textEn:
          'And much of what I stumbled into by following my curiosity and intuition turned out to be priceless later on.',
        textVi:
          'V\u00e0 ph\u1ea7n l\u1edbn nh\u1eefng g\u00ec t\u00f4i t\u00ecnh c\u1edd kh\u00e1m ph\u00e1 ra nh\u1edd \u0111i theo s\u1ef1 t\u00f2 m\u00f2 v\u00e0 tr\u1ef1c gi\u00e1c sau n\u00e0y h\u00f3a ra \u0111\u1ec1u l\u00e0 v\u00f4 gi\u00e1.',
        words: [
          'And',
          'much',
          'of',
          'what',
          'I',
          'stumbled',
          'into',
          'by',
          'following',
          'my',
          'curiosity',
          'and',
          'intuition',
          'turned',
          'out',
          'to',
          'be',
          'priceless',
          'later',
          'on.',
        ],
      },
      {
        id: 23,
        start: 244.0,
        duration: 12.0,
        end: 256.0,
        textEn:
          'You cannot connect the dots looking forward; you can only connect them looking backwards. So you have to trust that the dots will somehow connect in your future.',
        textVi:
          'B\u1ea1n kh\u00f4ng th\u1ec3 k\u1ebft n\u1ed1i c\u00e1c d\u1ea5u ch\u1ea5m khi nh\u00ecn v\u1ec1 ph\u00eda tr\u01b0\u1edbc; b\u1ea1n ch\u1ec9 c\u00f3 th\u1ec3 k\u1ebft n\u1ed1i ch\u00fang khi nh\u00ecn l\u1ea1i ph\u00eda sau. V\u00ec v\u1eady, b\u1ea1n ph\u1ea3i tin r\u1eb1ng c\u00e1c d\u1ea5u m\u1ed1c s\u1ebd b\u1eb1ng c\u00e1ch n\u00e0o \u0111\u00f3 k\u1ebft n\u1ed1i l\u1ea1i trong t\u01b0\u01a1ng lai c\u1ee7a b\u1ea1n.',
        words: [
          'You',
          'cannot',
          'connect',
          'the',
          'dots',
          'looking',
          'forward;',
          'you',
          'can',
          'only',
          'connect',
          'them',
          'looking',
          'backwards.',
          'So',
          'you',
          'have',
          'to',
          'trust',
          'that',
          'the',
          'dots',
          'will',
          'somehow',
          'connect',
          'in',
          'your',
          'future.',
        ],
      },
      {
        id: 24,
        start: 256.5,
        duration: 11.0,
        end: 267.5,
        textEn:
          'You have to trust in something \u2014 your gut, destiny, life, karma, whatever. This approach has never let me down, and it has made all the difference in my life.',
        textVi:
          'B\u1ea1n ph\u1ea3i tin v\u00e0o m\u1ed9t \u0111i\u1ec1u g\u00ec \u0111\u00f3 \u2014 linh c\u1ea3m, s\u1ed1 ph\u1eadn, cu\u1ed9c \u0111\u1eddi, nghi\u1ec7p ch\u01b0\u1edbng, b\u1ea5t c\u1ee9 \u0111i\u1ec1u g\u00ec. C\u00e1ch ngh\u0129 n\u00e0y ch\u01b0a bao gi\u1edd l\u00e0m t\u00f4i th\u1ea5t v\u1ecdng, v\u00e0 n\u00f3 \u0111\u00e3 t\u1ea1o n\u00ean t\u1ea5t c\u1ea3 s\u1ef1 kh\u00e1c bi\u1ec7t trong cu\u1ed9c \u0111\u1eddi t\u00f4i.',
        words: [
          'You',
          'have',
          'to',
          'trust',
          'in',
          'something',
          '\u2014',
          'your',
          'gut,',
          'destiny,',
          'life,',
          'karma,',
          'whatever.',
          'This',
          'approach',
          'has',
          'never',
          'let',
          'me',
          'down,',
          'and',
          'it',
          'has',
          'made',
          'all',
          'the',
          'difference',
          'in',
          'my',
          'life.',
        ],
      },
      {
        id: 25,
        start: 268.0,
        duration: 11.0,
        end: 279.0,
        textEn:
          'My second story is about love and loss. I was lucky \u2014 I found what I loved to do early in life.',
        textVi:
          'C\u00e2u chuy\u1ec7n th\u1ee9 hai c\u1ee7a t\u00f4i l\u00e0 v\u1ec1 t\u00ecnh y\u00eau v\u00e0 s\u1ef1 m\u1ea5t m\u00e1t. T\u00f4i \u0111\u00e3 may m\u1eafn \u2014 t\u00f4i t\u00ecm th\u1ea5y \u0111i\u1ec1u m\u00ecnh y\u00eau th\u00edch t\u1eeb r\u1ea5t s\u1edbm.',
        words: [
          'My',
          'second',
          'story',
          'is',
          'about',
          'love',
          'and',
          'loss.',
          'I',
          'was',
          'lucky',
          '\u2014',
          'I',
          'found',
          'what',
          'I',
          'loved',
          'to',
          'do',
          'early',
          'in',
          'life.',
        ],
      },
      {
        id: 26,
        start: 279.5,
        duration: 12.5,
        end: 292.0,
        textEn:
          'Woz and I started Apple in my parents garage when I was 20. We worked hard, and in 10 years Apple had grown into a $2 billion company with over 4000 employees.',
        textVi:
          'Woz v\u00e0 t\u00f4i \u0111\u00e3 s\u00e1ng l\u1eadp Apple trong gara c\u1ee7a b\u1ed1 m\u1eb9 khi t\u00f4i 20 tu\u1ed5i. Ch\u00fang t\u00f4i l\u00e0m vi\u1ec7c ch\u0103m ch\u1ec9, v\u00e0 trong 10 n\u0103m Apple \u0111\u00e3 ph\u00e1t tri\u1ec3n th\u00e0nh m\u1ed9t c\u00f4ng ty 2 t\u1ef7 \u0111\u00f4 la v\u1edbi h\u01a1n 4.000 nh\u00e2n vi\u00ean.',
        words: [
          'Woz',
          'and',
          'I',
          'started',
          'Apple',
          'in',
          'my',
          'parents',
          'garage',
          'when',
          'I',
          'was',
          '20.',
          'We',
          'worked',
          'hard,',
          'and',
          'in',
          '10',
          'years',
          'Apple',
          'had',
          'grown',
          'into',
          'a',
          '$2',
          'billion',
          'company',
          'with',
          'over',
          '4000',
          'employees.',
        ],
      },
      {
        id: 27,
        start: 292.5,
        duration: 11.5,
        end: 304.0,
        textEn:
          'We had just released our finest creation \u2014 the Macintosh \u2014 a year earlier, and I had just turned 30. And then I got fired.',
        textVi:
          'Ch\u00fang t\u00f4i v\u1eeba cho ra m\u1eaft t\u00e1c ph\u1ea9m tuy\u1ec7t v\u1eddi nh\u1ea5t \u2014 m\u00e1y t\u00ednh Macintosh \u2014 m\u1ed9t n\u0103m tr\u01b0\u1edbc \u0111\u00f3, v\u00e0 t\u00f4i v\u1eeba b\u01b0\u1edbc sang tu\u1ed5i 30. V\u00e0 r\u1ed3i t\u00f4i b\u1ecb sa th\u1ea3i.',
        words: [
          'We',
          'had',
          'just',
          'released',
          'our',
          'finest',
          'creation',
          '\u2014',
          'the',
          'Macintosh',
          '\u2014',
          'a',
          'year',
          'earlier,',
          'and',
          'I',
          'had',
          'just',
          'turned',
          '30.',
          'And',
          'then',
          'I',
          'got',
          'fired.',
        ],
      },
      {
        id: 28,
        start: 304.5,
        duration: 13.5,
        end: 318.0,
        textEn:
          'How can you get fired from a company you started? Well, as Apple grew we hired someone who I thought was very talented to run the company with me.',
        textVi:
          'L\u00e0m sao b\u1ea1n c\u00f3 th\u1ec3 b\u1ecb sa th\u1ea3i kh\u1ecfi c\u00f4ng ty do ch\u00ednh m\u00ecnh s\u00e1ng l\u1eadp? Khi Apple l\u1edbn m\u1ea1nh, ch\u00fang t\u00f4i \u0111\u00e3 thu\u00ea m\u1ed9t ng\u01b0\u1eddi m\u00e0 t\u00f4i ngh\u0129 r\u1ea5t t\u00e0i n\u0103ng v\u1ec1 \u0111i\u1ec1u h\u00e0nh c\u00f4ng ty c\u00f9ng t\u00f4i.',
        words: [
          'How',
          'can',
          'you',
          'get',
          'fired',
          'from',
          'a',
          'company',
          'you',
          'started?',
          'Well,',
          'as',
          'Apple',
          'grew',
          'we',
          'hired',
          'someone',
          'who',
          'I',
          'thought',
          'was',
          'very',
          'talented',
          'to',
          'run',
          'the',
          'company',
          'with',
          'me.',
        ],
      },
      {
        id: 29,
        start: 318.5,
        duration: 13.5,
        end: 332.0,
        textEn:
          'For the first year or so things went well. But then our visions of the future began to diverge and eventually we had a falling out.',
        textVi:
          'Trong n\u0103m \u0111\u1ea7u ti\u00ean m\u1ecdi chuy\u1ec7n su\u00f4n s\u1ebb. Nh\u01b0ng sau \u0111\u00f3 t\u1ea7m nh\u00ecn v\u1ec1 t\u01b0\u01a1ng lai c\u1ee7a ch\u00fang t\u00f4i b\u1eaft \u0111\u1ea7u r\u1ebd h\u01b0\u1edbng v\u00e0 cu\u1ed1i c\u00f9ng ch\u00fang t\u00f4i \u0111\u00e3 b\u1ea5t h\u00f2a.',
        words: [
          'For',
          'the',
          'first',
          'year',
          'or',
          'so',
          'things',
          'went',
          'well.',
          'But',
          'then',
          'our',
          'visions',
          'of',
          'the',
          'future',
          'began',
          'to',
          'diverge',
          'and',
          'eventually',
          'we',
          'had',
          'a',
          'falling',
          'out.',
        ],
      },
      {
        id: 30,
        start: 332.5,
        duration: 14.5,
        end: 347.0,
        textEn:
          'When we did, our Board of Directors sided with him. So at 30 I was out. What had been the focus of my entire adult life was gone, and it was devastating.',
        textVi:
          'Khi \u0111\u00f3, H\u1ed9i \u0111\u1ed3ng qu\u1ea3n tr\u1ecb \u0111\u00e3 \u0111\u1ee9ng v\u1ec1 ph\u00eda \u00f4ng \u1ea5y. Th\u1ebf l\u00e0 \u1edf tu\u1ed5i 30 t\u00f4i b\u1ecb \u0111u\u1ed5i vi\u1ec7c. Th\u1ee9 l\u00e0 t\u00e2m \u0111i\u1ec3m c\u1ee7a to\u00e0n b\u1ed9 cu\u1ed9c \u0111\u1eddi tr\u01b0\u1edfng th\u00e0nh c\u1ee7a t\u00f4i \u0111\u00e3 tan bi\u1ebfn, th\u1eadt t\u00e0n kh\u1ed1c.',
        words: [
          'When',
          'we',
          'did,',
          'our',
          'Board',
          'of',
          'Directors',
          'sided',
          'with',
          'him.',
          'So',
          'at',
          '30',
          'I',
          'was',
          'out.',
          'What',
          'had',
          'been',
          'the',
          'focus',
          'of',
          'my',
          'entire',
          'adult',
          'life',
          'was',
          'gone,',
          'and',
          'it',
          'was',
          'devastating.',
        ],
      },
      {
        id: 31,
        start: 347.5,
        duration: 14.5,
        end: 362.0,
        textEn:
          "I really didn't know what to do for a few months. But something slowly began to dawn on me \u2014 I still loved what I did. And so I decided to start over.",
        textVi:
          'T\u00f4i th\u1ef1c s\u1ef1 kh\u00f4ng bi\u1ebft ph\u1ea3i l\u00e0m g\u00ec trong v\u00e0i th\u00e1ng. Nh\u01b0ng c\u00f3 m\u1ed9t \u0111i\u1ec1u g\u00ec \u0111\u00f3 d\u1ea7n b\u1eebng s\u00e1ng trong t\u00f4i \u2014 t\u00f4i v\u1eabn c\u00f2n r\u1ea5t y\u00eau nh\u1eefng g\u00ec m\u00ecnh l\u00e0m. V\u00e0 t\u00f4i quy\u1ebft \u0111\u1ecbnh b\u1eaft \u0111\u1ea7u l\u1ea1i t\u1eeb \u0111\u1ea7u.',
        words: [
          'I',
          'really',
          "didn't",
          'know',
          'what',
          'to',
          'do',
          'for',
          'a',
          'few',
          'months.',
          'But',
          'something',
          'slowly',
          'began',
          'to',
          'dawn',
          'on',
          'me',
          '\u2014',
          'I',
          'still',
          'loved',
          'what',
          'I',
          'did.',
          'And',
          'so',
          'I',
          'decided',
          'to',
          'start',
          'over.',
        ],
      },
      {
        id: 32,
        start: 362.5,
        duration: 14.5,
        end: 377.0,
        textEn:
          'It turned out that getting fired from Apple was the best thing that could have ever happened to me. The heaviness of being successful was replaced by the lightness of being a beginner again.',
        textVi:
          'H\u00f3a ra vi\u1ec7c b\u1ecb sa th\u1ea3i kh\u1ecfi Apple l\u1ea1i l\u00e0 \u0111i\u1ec1u tuy\u1ec7t v\u1eddi nh\u1ea5t t\u1eebng x\u1ea3y \u0111\u1ebfn v\u1edbi t\u00f4i. S\u1ef1 n\u1eb7ng n\u1ec1 c\u1ee7a vi\u1ec7c th\u00e0nh c\u00f4ng \u0111\u00e3 \u0111\u01b0\u1ee3c thay th\u1ebf b\u1eb1ng s\u1ef1 nh\u1eb9 nh\u00f5m khi l\u1ea1i \u0111\u01b0\u1ee3c l\u00e0m m\u1ed9t ng\u01b0\u1eddi m\u1edbi b\u1eaft \u0111\u1ea7u.',
        words: [
          'It',
          'turned',
          'out',
          'that',
          'getting',
          'fired',
          'from',
          'Apple',
          'was',
          'the',
          'best',
          'thing',
          'that',
          'could',
          'have',
          'ever',
          'happened',
          'to',
          'me.',
          'The',
          'heaviness',
          'of',
          'being',
          'successful',
          'was',
          'replaced',
          'by',
          'the',
          'lightness',
          'of',
          'being',
          'a',
          'beginner',
          'again.',
        ],
      },
      {
        id: 33,
        start: 377.5,
        duration: 14.5,
        end: 392.0,
        textEn:
          'During the next five years, I started a company named NeXT, another company named Pixar, and fell in love with an amazing woman who would become my wife.',
        textVi:
          'Trong 5 n\u0103m ti\u1ebfp theo, t\u00f4i th\u00e0nh l\u1eadp c\u00f4ng ty NeXT, c\u00f4ng ty Pixar, v\u00e0 \u0111em l\u00f2ng y\u00eau m\u1ed9t ng\u01b0\u1eddi ph\u1ee5 n\u1eef tuy\u1ec7t v\u1eddi ng\u01b0\u1eddi sau n\u00e0y tr\u1edf th\u00e0nh v\u1ee3 t\u00f4i.',
        words: [
          'During',
          'the',
          'next',
          'five',
          'years,',
          'I',
          'started',
          'a',
          'company',
          'named',
          'NeXT,',
          'another',
          'company',
          'named',
          'Pixar,',
          'and',
          'fell',
          'in',
          'love',
          'with',
          'an',
          'amazing',
          'woman',
          'who',
          'would',
          'become',
          'my',
          'wife.',
        ],
      },
      {
        id: 34,
        start: 392.5,
        duration: 14.5,
        end: 407.0,
        textEn:
          'Pixar went on to create the worlds first computer animated feature film, Toy Story, and is now the most successful animation studio in the world.',
        textVi:
          'Pixar ti\u1ebfp t\u1ee5c t\u1ea1o ra b\u1ed9 phim ho\u1ea1t h\u00ecnh v\u1ebd b\u1eb1ng m\u00e1y t\u00ednh \u0111\u1ea7u ti\u00ean tr\u00ean th\u1ebf gi\u1edbi, Toy Story, v\u00e0 hi\u1ec7n l\u00e0 h\u00e3ng phim ho\u1ea1t h\u00ecnh th\u00e0nh c\u00f4ng nh\u1ea5t tr\u00ean th\u1ebf gi\u1edbi.',
        words: [
          'Pixar',
          'went',
          'on',
          'to',
          'create',
          'the',
          'worlds',
          'first',
          'computer',
          'animated',
          'feature',
          'film,',
          'Toy',
          'Story,',
          'and',
          'is',
          'now',
          'the',
          'most',
          'successful',
          'animation',
          'studio',
          'in',
          'the',
          'world.',
        ],
      },
      {
        id: 35,
        start: 407.5,
        duration: 14.5,
        end: 422.0,
        textEn:
          "In a remarkable turn of events, Apple bought NeXT, I returned to Apple, and the technology we developed at NeXT is at the heart of Apple's current renaissance.",
        textVi:
          'Trong m\u1ed9t b\u01b0\u1edbc ngo\u1eb7t \u0111\u00e1ng kinh ng\u1ea1c, Apple \u0111\u00e3 mua l\u1ea1i NeXT, t\u00f4i tr\u1edf l\u1ea1i Apple, v\u00e0 c\u00f4ng ngh\u1ec7 ch\u00fang t\u00f4i ph\u00e1t tri\u1ec3n t\u1ea1i NeXT ch\u00ednh l\u00e0 tr\u00e1i tim c\u1ee7a s\u1ef1 h\u1ed3i sinh c\u1ee7a Apple hi\u1ec7n nay.',
        words: [
          'In',
          'a',
          'remarkable',
          'turn',
          'of',
          'events,',
          'Apple',
          'bought',
          'NeXT,',
          'I',
          'returned',
          'to',
          'Apple,',
          'and',
          'the',
          'technology',
          'we',
          'developed',
          'at',
          'NeXT',
          'is',
          'at',
          'the',
          'heart',
          'of',
          "Apple's",
          'current',
          'renaissance.',
        ],
      },
      {
        id: 36,
        start: 422.5,
        duration: 14.5,
        end: 437.0,
        textEn:
          "Sometimes life hits you in the head with a brick. Don't lose faith. The only way to do great work is to love what you do. If you haven't found it yet, keep looking. Don't settle.",
        textVi:
          '\u0110\u00f4i khi cu\u1ed9c \u0111\u1eddi s\u1ebd gi\u00e1ng v\u00e0o \u0111\u1ea7u b\u1ea1n m\u1ed9t vi\u00ean g\u1ea1ch. \u0110\u1eebng \u0111\u00e1nh m\u1ea5t ni\u1ec1m tin. C\u00e1ch duy nh\u1ea5t \u0111\u1ec3 l\u00e0m c\u00f4ng vi\u1ec7c v\u0129 \u0111\u1ea1i l\u00e0 y\u00eau vi\u1ec7c b\u1ea1n l\u00e0m. N\u1ebfu b\u1ea1n ch\u01b0a t\u00ecm th\u1ea5y, h\u00e3y ti\u1ebfp t\u1ee5c t\u00ecm ki\u1ebfm. \u0110\u1eebng an ph\u1eadn.',
        words: [
          'Sometimes',
          'life',
          'hits',
          'you',
          'in',
          'the',
          'head',
          'with',
          'a',
          'brick.',
          "Don't",
          'lose',
          'faith.',
          'The',
          'only',
          'way',
          'to',
          'do',
          'great',
          'work',
          'is',
          'to',
          'love',
          'what',
          'you',
          'do.',
          'If',
          'you',
          "haven't",
          'found',
          'it',
          'yet,',
          'keep',
          'looking.',
          "Don't",
          'settle.',
        ],
      },
      {
        id: 37,
        start: 437.5,
        duration: 11.5,
        end: 449.0,
        textEn:
          "My third story is about death. When I was 17, I read a quote that went something like: 'If you live each day as if it was your last, someday you'll most certainly be right.'",
        textVi:
          "C\u00e2u chuy\u1ec7n th\u1ee9 ba c\u1ee7a t\u00f4i l\u00e0 v\u1ec1 c\u00e1i ch\u1ebft. N\u0103m 17 tu\u1ed5i, t\u00f4i \u0111\u1ecdc \u0111\u01b0\u1ee3c m\u1ed9t c\u00e2u n\u00f3i: 'N\u1ebfu b\u1ea1n s\u1ed1ng m\u1ed7i ng\u00e0y nh\u01b0 th\u1ec3 \u0111\u00f3 l\u00e0 ng\u00e0y cu\u1ed1i c\u00f9ng, m\u1ed9t ng\u00e0y n\u00e0o \u0111\u00f3 b\u1ea1n ch\u1eafc ch\u1eafn s\u1ebd \u0111\u00fang.'",
        words: [
          'My',
          'third',
          'story',
          'is',
          'about',
          'death.',
          'When',
          'I',
          'was',
          '17,',
          'I',
          'read',
          'a',
          'quote',
          'that',
          'went',
          'something',
          'like:',
          "'If",
          'you',
          'live',
          'each',
          'day',
          'as',
          'if',
          'it',
          'was',
          'your',
          'last,',
          'someday',
          "you'll",
          'most',
          'certainly',
          'be',
          "right.'",
        ],
      },
      {
        id: 38,
        start: 449.5,
        duration: 14.5,
        end: 464.0,
        textEn:
          "Since then, for the past 33 years, I have looked in the mirror every morning and asked myself: 'If today were the last day of my life, would I want to do what I am about to do today?'",
        textVi:
          "K\u1ec3 t\u1eeb \u0111\u00f3, su\u1ed1t 33 n\u0103m qua, m\u1ed7i s\u00e1ng t\u00f4i \u0111\u1ec1u nh\u00ecn v\u00e0o g\u01b0\u01a1ng v\u00e0 t\u1ef1 h\u1ecfi: 'N\u1ebfu h\u00f4m nay l\u00e0 ng\u00e0y cu\u1ed1i c\u00f9ng c\u1ee7a \u0111\u1eddi m\u00ecnh, m\u00ecnh c\u00f3 mu\u1ed1n l\u00e0m \u0111i\u1ec1u m\u00ecnh chu\u1ea9n b\u1ecb l\u00e0m h\u00f4m nay kh\u00f4ng?'",
        words: [
          'Since',
          'then,',
          'for',
          'the',
          'past',
          '33',
          'years,',
          'I',
          'have',
          'looked',
          'in',
          'the',
          'mirror',
          'every',
          'morning',
          'and',
          'asked',
          'myself:',
          "'If",
          'today',
          'were',
          'the',
          'last',
          'day',
          'of',
          'my',
          'life,',
          'would',
          'I',
          'want',
          'to',
          'do',
          'what',
          'I',
          'am',
          'about',
          'to',
          'do',
          "today?'",
        ],
      },
      {
        id: 39,
        start: 464.5,
        duration: 13.5,
        end: 478.0,
        textEn:
          "Remembering that I'll be dead soon is the most important tool I've ever encountered to help me make the big choices in life.",
        textVi:
          'Vi\u1ec7c ghi nh\u1edb r\u1eb1ng m\u00ecnh s\u1ebd s\u1edbm ch\u1ebft \u0111i l\u00e0 c\u00f4ng c\u1ee5 quan tr\u1ecdng nh\u1ea5t t\u00f4i t\u1eebng c\u00f3 \u0111\u1ec3 gi\u00fap t\u00f4i \u0111\u01b0a ra nh\u1eefng quy\u1ebft \u0111\u1ecbnh l\u1edbn trong \u0111\u1eddi.',
        words: [
          'Remembering',
          'that',
          "I'll",
          'be',
          'dead',
          'soon',
          'is',
          'the',
          'most',
          'important',
          'tool',
          "I've",
          'ever',
          'encountered',
          'to',
          'help',
          'me',
          'make',
          'the',
          'big',
          'choices',
          'in',
          'life.',
        ],
      },
      {
        id: 40,
        start: 478.5,
        duration: 14.5,
        end: 493.0,
        textEn:
          'Because almost everything \u2014 all external expectations, all pride, all fear of embarrassment or failure \u2014 these things just fall away in the face of death, leaving only what is truly important.',
        textVi:
          'B\u1edfi v\u00ec h\u1ea7u nh\u01b0 m\u1ecdi th\u1ee9 \u2014 t\u1ea5t c\u1ea3 k\u1ef3 v\u1ecdng b\u00ean ngo\u00e0i, ni\u1ec1m ki\u00eau h\u00e3nh, n\u1ed7i s\u1ee3 x\u1ea5u h\u1ed5 hay th\u1ea5t b\u1ea1i \u2014 t\u1ea5t c\u1ea3 \u0111\u1ec1u tan bi\u1ebfn tr\u01b0\u1edbc c\u00e1i ch\u1ebft, ch\u1ec9 \u0111\u1ec3 l\u1ea1i nh\u1eefng g\u00ec th\u1ef1c s\u1ef1 quan tr\u1ecdng.',
        words: [
          'Because',
          'almost',
          'everything',
          '\u2014',
          'all',
          'external',
          'expectations,',
          'all',
          'pride,',
          'all',
          'fear',
          'of',
          'embarrassment',
          'or',
          'failure',
          '\u2014',
          'these',
          'things',
          'just',
          'fall',
          'away',
          'in',
          'the',
          'face',
          'of',
          'death,',
          'leaving',
          'only',
          'what',
          'is',
          'truly',
          'important.',
        ],
      },
      {
        id: 41,
        start: 493.5,
        duration: 14.5,
        end: 508.0,
        textEn:
          'About a year ago I was diagnosed with cancer. The doctors told me this was almost certainly a type of cancer that is incurable, and that I should expect to live no longer than three to six months.',
        textVi:
          'Kho\u1ea3ng m\u1ed9t n\u0103m tr\u01b0\u1edbc t\u00f4i \u0111\u01b0\u1ee3c ch\u1ea9n \u0111o\u00e1n m\u1eafc b\u1ec7nh ung th\u01b0. C\u00e1c b\u00e1c s\u0129 b\u1ea3o t\u00f4i r\u1eb1ng \u0111\u00e2y g\u1ea7n nh\u01b0 ch\u1eafc ch\u1eafn l\u00e0 lo\u1ea1i ung th\u01b0 kh\u00f4ng th\u1ec3 ch\u1eefa kh\u1ecfi, v\u00e0 t\u00f4i ch\u1ec9 n\u00ean chu\u1ea9n b\u1ecb tinh th\u1ea7n s\u1ed1ng kh\u00f4ng qu\u00e1 3 \u0111\u1ebfn 6 th\u00e1ng.',
        words: [
          'About',
          'a',
          'year',
          'ago',
          'I',
          'was',
          'diagnosed',
          'with',
          'cancer.',
          'The',
          'doctors',
          'told',
          'me',
          'this',
          'was',
          'almost',
          'certainly',
          'a',
          'type',
          'of',
          'cancer',
          'that',
          'is',
          'incurable,',
          'and',
          'that',
          'I',
          'should',
          'expect',
          'to',
          'live',
          'no',
          'longer',
          'than',
          'three',
          'to',
          'six',
          'months.',
        ],
      },
      {
        id: 42,
        start: 508.5,
        duration: 14.5,
        end: 523.0,
        textEn:
          "Later that evening I had a biopsy, and it turned out to be a very rare form of pancreatic cancer that is curable with surgery. I had the surgery and I'm fine now.",
        textVi:
          'T\u1ed1i mu\u1ed9n h\u00f4m \u0111\u00f3 t\u00f4i l\u00e0m sinh thi\u1ebft, v\u00e0 h\u00f3a ra \u0111\u00f3 l\u00e0 m\u1ed9t d\u1ea1ng ung th\u01b0 tuy\u1ebfn t\u1ee5y c\u1ef1c k\u1ef3 hi\u1ebfm g\u1eb7p c\u00f3 th\u1ec3 ch\u1eefa kh\u1ecfi b\u1eb1ng ph\u1eabu thu\u1eadt. T\u00f4i \u0111\u00e3 ph\u1eabu thu\u1eadt v\u00e0 hi\u1ec7n t\u1ea1i t\u00f4i ho\u00e0n to\u00e0n kh\u1ecfe m\u1ea1nh.',
        words: [
          'Later',
          'that',
          'evening',
          'I',
          'had',
          'a',
          'biopsy,',
          'and',
          'it',
          'turned',
          'out',
          'to',
          'be',
          'a',
          'very',
          'rare',
          'form',
          'of',
          'pancreatic',
          'cancer',
          'that',
          'is',
          'curable',
          'with',
          'surgery.',
          'I',
          'had',
          'the',
          'surgery',
          'and',
          "I'm",
          'fine',
          'now.',
        ],
      },
      {
        id: 43,
        start: 523.5,
        duration: 14.5,
        end: 538.0,
        textEn:
          "No one wants to die. Even people who want to go to heaven don't want to die to get there. And yet death is the destination we all share. No one has ever escaped it.",
        textVi:
          'Kh\u00f4ng ai mu\u1ed1n ch\u1ebft c\u1ea3. Ngay c\u1ea3 nh\u1eefng ng\u01b0\u1eddi mu\u1ed1n l\u00ean thi\u00ean \u0111\u00e0ng c\u0169ng kh\u00f4ng mu\u1ed1n ch\u1ebft \u0111\u1ec3 \u0111\u1ebfn \u0111\u01b0\u1ee3c \u0111\u00f3. V\u1eady m\u00e0 c\u00e1i ch\u1ebft l\u1ea1i l\u00e0 \u0111\u00edch \u0111\u1ebfn chung c\u1ee7a t\u1ea5t c\u1ea3 ch\u00fang ta. Ch\u01b0a t\u1eebng c\u00f3 ai tr\u1ed1n tho\u00e1t kh\u1ecfi n\u00f3.',
        words: [
          'No',
          'one',
          'wants',
          'to',
          'die.',
          'Even',
          'people',
          'who',
          'want',
          'to',
          'go',
          'to',
          'heaven',
          "don't",
          'want',
          'to',
          'die',
          'to',
          'get',
          'there.',
          'And',
          'yet',
          'death',
          'is',
          'the',
          'destination',
          'we',
          'all',
          'share.',
          'No',
          'one',
          'has',
          'ever',
          'escaped',
          'it.',
        ],
      },
      {
        id: 44,
        start: 538.5,
        duration: 14.5,
        end: 553.0,
        textEn:
          "Death is very likely the single best invention of Life. It is Life's change agent. It clears out the old to make way for the new.",
        textVi:
          'C\u00e1i Ch\u1ebft r\u1ea5t c\u00f3 th\u1ec3 l\u00e0 ph\u00e1t minh duy nh\u1ea5t tuy\u1ec7t v\u1eddi nh\u1ea5t c\u1ee7a S\u1ef1 S\u1ed1ng. N\u00f3 l\u00e0 t\u00e1c nh\u00e2n thay \u0111\u1ed5i c\u1ee7a S\u1ef1 S\u1ed1ng. N\u00f3 d\u1ecdn s\u1ea1ch c\u00e1i c\u0169 \u0111\u1ec3 m\u1edf \u0111\u01b0\u1eddng cho c\u00e1i m\u1edbi.',
        words: [
          'Death',
          'is',
          'very',
          'likely',
          'the',
          'single',
          'best',
          'invention',
          'of',
          'Life.',
          'It',
          'is',
          "Life's",
          'change',
          'agent.',
          'It',
          'clears',
          'out',
          'the',
          'old',
          'to',
          'make',
          'way',
          'for',
          'the',
          'new.',
        ],
      },
      {
        id: 45,
        start: 553.5,
        duration: 14.5,
        end: 568.0,
        textEn:
          "Your time is limited, so don't waste it living someone else's life. Don't be trapped by dogma \u2014 which is living with the results of other people's thinking.",
        textVi:
          'Th\u1eddi gian c\u1ee7a c\u00e1c b\u1ea1n c\u00f3 h\u1ea1n, v\u00ec v\u1eady \u0111\u1eebng l\u00e3ng ph\u00ed n\u00f3 \u0111\u1ec3 s\u1ed1ng cu\u1ed9c \u0111\u1eddi c\u1ee7a ng\u01b0\u1eddi kh\u00e1c. \u0110\u1eebng b\u1ecb m\u1eafc k\u1eb9t b\u1edfi gi\u00e1o \u0111i\u1ec1u \u2014 t\u1ee9c l\u00e0 s\u1ed1ng b\u1eb1ng k\u1ebft qu\u1ea3 suy ngh\u0129 c\u1ee7a ng\u01b0\u1eddi kh\u00e1c.',
        words: [
          'Your',
          'time',
          'is',
          'limited,',
          'so',
          "don't",
          'waste',
          'it',
          'living',
          'someone',
          "else's",
          'life.',
          "Don't",
          'be',
          'trapped',
          'by',
          'dogma',
          '\u2014',
          'which',
          'is',
          'living',
          'with',
          'the',
          'results',
          'of',
          'other',
          "people's",
          'thinking.',
        ],
      },
      {
        id: 46,
        start: 568.5,
        duration: 14.5,
        end: 583.0,
        textEn:
          'And most important, have the courage to follow your heart and intuition. They somehow already know what you truly want to become. Everything else is secondary.',
        textVi:
          'V\u00e0 quan tr\u1ecdng nh\u1ea5t, h\u00e3y c\u00f3 can \u0111\u1ea3m \u0111i theo tr\u00e1i tim v\u00e0 tr\u1ef1c gi\u00e1c c\u1ee7a b\u1ea1n. B\u1eb1ng c\u00e1ch n\u00e0o \u0111\u00f3 ch\u00fang \u0111\u00e3 bi\u1ebft b\u1ea1n th\u1ef1c s\u1ef1 mu\u1ed1n tr\u1edf th\u00e0nh ai r\u1ed3i. M\u1ecdi th\u1ee9 kh\u00e1c ch\u1ec9 l\u00e0 th\u1ee9 y\u1ebfu.',
        words: [
          'And',
          'most',
          'important,',
          'have',
          'the',
          'courage',
          'to',
          'follow',
          'your',
          'heart',
          'and',
          'intuition.',
          'They',
          'somehow',
          'already',
          'know',
          'what',
          'you',
          'truly',
          'want',
          'to',
          'become.',
          'Everything',
          'else',
          'is',
          'secondary.',
        ],
      },
      {
        id: 47,
        start: 583.5,
        duration: 14.5,
        end: 598.0,
        textEn:
          "When I was young, there was an amazing publication called The Whole Earth Catalog. On the back cover of their final issue were the words: 'Stay Hungry. Stay Foolish.'",
        textVi:
          "Khi t\u00f4i c\u00f2n tr\u1ebb, c\u00f3 m\u1ed9t \u1ea5n ph\u1ea9m tuy\u1ec7t v\u1eddi mang t\u00ean The Whole Earth Catalog. \u1ede b\u00eca sau s\u1ed1 cu\u1ed1i c\u00f9ng c\u00f3 d\u00f2ng ch\u1eef: 'H\u00e3y lu\u00f4n khao kh\u00e1t. H\u00e3y lu\u00f4n d\u1ea1i kh\u1edd.'",
        words: [
          'When',
          'I',
          'was',
          'young,',
          'there',
          'was',
          'an',
          'amazing',
          'publication',
          'called',
          'The',
          'Whole',
          'Earth',
          'Catalog.',
          'On',
          'the',
          'back',
          'cover',
          'of',
          'their',
          'final',
          'issue',
          'were',
          'the',
          'words:',
          "'Stay",
          'Hungry.',
          'Stay',
          "Foolish.'",
        ],
      },
      {
        id: 48,
        start: 598.5,
        duration: 14.5,
        end: 613.0,
        textEn:
          'Stay Hungry. Stay Foolish. And I have always wished that for myself. And now, as you graduate to begin anew, I wish that for you: Stay Hungry. Stay Foolish. Thank you all very much.',
        textVi:
          'H\u00e3y lu\u00f4n khao kh\u00e1t. H\u00e3y lu\u00f4n d\u1ea1i kh\u1edd. V\u00e0 t\u00f4i lu\u00f4n mong \u01b0\u1edbc \u0111i\u1ec1u \u0111\u00f3 cho ch\u00ednh m\u00ecnh. V\u00e0 gi\u1edd \u0111\u00e2y, khi c\u00e1c b\u1ea1n t\u1ed1t nghi\u1ec7p \u0111\u1ec3 b\u1eaft \u0111\u1ea7u l\u1ea1i t\u1eeb \u0111\u1ea7u, t\u00f4i xin ch\u00fac c\u00e1c b\u1ea1n \u0111i\u1ec1u \u0111\u00f3: H\u00e3y lu\u00f4n khao kh\u00e1t. H\u00e3y lu\u00f4n d\u1ea1i kh\u1edd. C\u1ea3m \u01a1n t\u1ea5t c\u1ea3 c\u00e1c b\u1ea1n r\u1ea5t nhi\u1ec1u.',
        words: [
          'Stay',
          'Hungry.',
          'Stay',
          'Foolish.',
          'And',
          'I',
          'have',
          'always',
          'wished',
          'that',
          'for',
          'myself.',
          'And',
          'now,',
          'as',
          'you',
          'graduate',
          'to',
          'begin',
          'anew,',
          'I',
          'wish',
          'that',
          'for',
          'you:',
          'Stay',
          'Hungry.',
          'Stay',
          'Foolish.',
          'Thank',
          'you',
          'all',
          'very',
          'much.',
        ],
      },
    ],
  },
  {
    info: {
      videoId: 'iG9CE55wbtY',
      title: 'How to Learn Any Language in 6 Months | Chris Lonsdale | TEDx',
      channel: 'TEDx Talks',
      thumbnailUrl: 'https://img.youtube.com/vi/iG9CE55wbtY/hqdefault.jpg',
      durationFormatted: '18:26',
    },
    sampleCues: [
      {
        id: 1,
        start: 0.0,
        duration: 10.0,
        end: 10.0,
        textEn: 'Welcome to TEDx. How to learn any language in six months by Chris Lonsdale.',
        textVi:
          'Ch\u00e0o m\u1eebng \u0111\u1ebfn v\u1edbi TEDx. C\u00e1ch h\u1ecdc b\u1ea5t k\u1ef3 ng\u00f4n ng\u1eef n\u00e0o trong 6 th\u00e1ng b\u1edfi Chris Lonsdale.',
        words: [
          'Welcome',
          'to',
          'TEDx.',
          'How',
          'to',
          'learn',
          'any',
          'language',
          'in',
          'six',
          'months',
          'by',
          'Chris',
          'Lonsdale.',
        ],
      },
      {
        id: 2,
        start: 10.5,
        duration: 11.5,
        end: 22.0,
        textEn: 'Have you ever wondered why some people learn languages so fast?',
        textVi:
          'B\u1ea1n \u0111\u00e3 bao gi\u1edd t\u1ef1 h\u1ecfi t\u1ea1i sao m\u1ed9t s\u1ed1 ng\u01b0\u1eddi h\u1ecdc ngo\u1ea1i ng\u1eef l\u1ea1i nhanh \u0111\u1ebfn v\u1eady?',
        words: [
          'Have',
          'you',
          'ever',
          'wondered',
          'why',
          'some',
          'people',
          'learn',
          'languages',
          'so',
          'fast?',
        ],
      },
      {
        id: 3,
        start: 22.5,
        duration: 12.5,
        end: 35.0,
        textEn: 'Is it talent? Is it luck? Or is it something else that anyone can learn?',
        textVi:
          '\u0110\u00f3 l\u00e0 do n\u0103ng khi\u1ebfu? Do may m\u1eafn? Hay l\u00e0 do m\u1ed9t ph\u01b0\u01a1ng ph\u00e1p n\u00e0o \u0111\u00f3 m\u00e0 b\u1ea5t k\u1ef3 ai c\u0169ng c\u00f3 th\u1ec3 h\u1ecdc \u0111\u01b0\u1ee3c?',
        words: [
          'Is',
          'it',
          'talent?',
          'Is',
          'it',
          'luck?',
          'Or',
          'is',
          'it',
          'something',
          'else',
          'that',
          'anyone',
          'can',
          'learn?',
        ],
      },
      {
        id: 4,
        start: 35.5,
        duration: 13.5,
        end: 49.0,
        textEn:
          'The secret is not about talent; it is about applying the right principles and actions.',
        textVi:
          'B\u00ed quy\u1ebft kh\u00f4ng n\u1eb1m \u1edf t\u00e0i n\u0103ng; m\u00e0 l\u00e0 \u1edf vi\u1ec7c \u00e1p d\u1ee5ng \u0111\u00fang c\u00e1c nguy\u00ean t\u1eafc v\u00e0 h\u00e0nh \u0111\u1ed9ng ph\u00f9 h\u1ee3p.',
        words: [
          'The',
          'secret',
          'is',
          'not',
          'about',
          'talent;',
          'it',
          'is',
          'about',
          'applying',
          'the',
          'right',
          'principles',
          'and',
          'actions.',
        ],
      },
      {
        id: 5,
        start: 49.5,
        duration: 12.0,
        end: 61.5,
        textEn:
          'Principle 1: Focus on language content that is relevant to you and your daily survival.',
        textVi:
          'Nguy\u00ean t\u1eafc 1: T\u1eadp trung v\u00e0o n\u1ed9i dung ng\u00f4n ng\u1eef c\u00f3 li\u00ean quan tr\u1ef1c ti\u1ebfp \u0111\u1ebfn b\u1ea1n v\u00e0 s\u1ef1 sinh t\u1ed3n h\u00e0ng ng\u00e0y c\u1ee7a b\u1ea1n.',
        words: [
          'Principle',
          '1:',
          'Focus',
          'on',
          'language',
          'content',
          'that',
          'is',
          'relevant',
          'to',
          'you',
          'and',
          'your',
          'daily',
          'survival.',
        ],
      },
      {
        id: 6,
        start: 62.0,
        duration: 14.0,
        end: 76.0,
        textEn:
          'Principle 2: Use your new language as a tool to communicate from day one, not just as knowledge to store.',
        textVi:
          'Nguy\u00ean t\u1eafc 2: H\u00e3y s\u1eed d\u1ee5ng ng\u00f4n ng\u1eef m\u1edbi nh\u01b0 m\u1ed9t c\u00f4ng c\u1ee5 giao ti\u1ebfp ngay t\u1eeb ng\u00e0y \u0111\u1ea7u ti\u00ean, ch\u1ee9 kh\u00f4ng ch\u1ec9 l\u00e0 ki\u1ebfn th\u1ee9c \u0111\u1ec3 l\u01b0u tr\u1eef.',
        words: [
          'Principle',
          '2:',
          'Use',
          'your',
          'new',
          'language',
          'as',
          'a',
          'tool',
          'to',
          'communicate',
          'from',
          'day',
          'one,',
          'not',
          'just',
          'as',
          'knowledge',
          'to',
          'store.',
        ],
      },
    ],
  },
]

export function extractYouTubeVideoId(urlOrId: string): string | null {
  if (!urlOrId) return null
  const trimmed = urlOrId.trim()
  if (/^[a-zA-Z0-9_-]{11}$/.test(trimmed)) {
    return trimmed
  }
  const match = trimmed.match(
    /(?:youtu\.be\/|youtube\.com\/(?:embed\/|v\/|watch\?v=|watch\?.+&v=|shorts\/))([a-zA-Z0-9_-]{11})/,
  )
  return match ? match[1] : null
}

export async function fetchYouTubeBilingualTranscript(videoId: string): Promise<TranscriptCue[]> {
  const found = CURATED_LEARNING_VIDEOS.find((v) => v.info.videoId === videoId)
  if (found) {
    return found.sampleCues
  }

  // Fallback for custom videos
  return [
    {
      id: 1,
      start: 0,
      duration: 5,
      end: 5,
      textEn: 'Welcome to this English video lesson.',
      textVi: 'Chào mừng bạn đến với bài học tiếng Anh qua video này.',
      words: ['Welcome', 'to', 'this', 'English', 'video', 'lesson.'],
    },
    {
      id: 2,
      start: 5,
      duration: 6,
      end: 11,
      textEn:
        'Click any word in the transcript below to see its definition and add it to your flashcards.',
      textVi:
        'Nhấp vào bất kỳ từ nào trong phụ đề bên dưới để xem định nghĩa và thêm vào flashcard của bạn.',
      words: [
        'Click',
        'any',
        'word',
        'in',
        'the',
        'transcript',
        'below',
        'to',
        'see',
        'its',
        'definition',
        'and',
        'add',
        'it',
        'to',
        'your',
        'flashcards.',
      ],
    },
  ]
}
