import json
import os

from generate_complete_data import make_topic, write_stage

topics_raw = [
    ("s1_01_svo", "Cấu Trúc S-V-O & Hành Động Hàng Ngày", "S-V-O Daily Habits", "Nắm vững trật tự từ cơ bản Chủ ngữ + Động từ + Tân ngữ (S + V + O + Time/Place).", "Activity", "Beginner", [
        ("I drink fresh coffee every morning.", "Tôi uống cà phê tươi mỗi buổi sáng.", "S + V + O + Time", "Thì hiện tại đơn diễn tả thói quen lặp đi lặp lại."),
        ("She reads books before going to bed.", "Cô ấy đọc sách trước khi đi ngủ.", "S + V + O + Time", "Thêm 's/es' với chủ ngữ ngôi thứ 3 số ít (She/He/It)."),
        ("We eat breakfast at seven o'clock.", "Chúng tôi ăn bữa sáng lúc bảy giờ.", "S + V + O + Time", "Giới từ 'at' đứng trước mốc giờ cụ thể."),
        ("He plays football with his friends on Sundays.", "Anh ấy chơi bóng đá với bạn bè vào các ngày Chủ nhật.", "S + V + O + Place + Time", "Giới từ 'on' đứng trước các ngày trong tuần."),
        ("They study English at the library every afternoon.", "Họ học tiếng Anh tại thư viện mỗi buổi chiều.", "S + V + O + Place + Time", "Quy tắc nơi chốn (Place) đứng trước thời gian (Time)."),
        ("My mother cooks dinner for our family every evening.", "Mẹ tôi nấu bữa tối cho gia đình vào mỗi buổi tối.", "S + V + O + Target + Time", "Chủ ngữ số ít 'My mother' đi với động từ thêm 's'."),
        ("The company develops software for international clients.", "Công ty phát triển phần mềm cho các khách hàng quốc tế.", "S + V + O + Target", "Động từ 'develop' đi kèm tân ngữ trực tiếp."),
        ("I check my email first thing in the morning.", "Tôi kiểm tra email là việc đầu tiên vào buổi sáng.", "S + V + O + Time", "Cụm 'first thing in the morning' đặt cuối câu bổ nghĩa thời gian."),
        ("She teaches mathematics at a local high school.", "Cô ấy dạy môn toán tại một trường trung học địa phương.", "S + V + O + Place", "Động từ 'teach' đổi thành 'teaches'."),
        ("We clean our house thoroughly every weekend.", "Chúng tôi dọn dẹp nhà cửa cẩn thận vào mỗi cuối tuần.", "S + V + O + Manner + Time", "Trạng từ 'thoroughly' chỉ mức độ/cách thức."),
        ("He drives a car to work every day.", "Anh ấy lái xe ô tô đi làm mỗi ngày.", "S + V + O + Destination + Time", "Cụm 'to work' chỉ đích đến."),
        ("They practice speaking English with native teachers.", "Họ luyện nói tiếng Anh với các giáo viên bản xứ.", "S + V + V-ing + O + Partner", "Sau 'practice' luôn là động từ dạng V-ing."),
        ("My brother listens to music when he studies.", "Anh trai tôi nghe nhạc khi anh ấy học bài.", "S + V + O + Clause", "'listen' luôn đi với giới từ 'to'."),
        ("She writes articles for an online magazine.", "Cô ấy viết các bài báo cho một tạp chí trực tuyến.", "S + V + O + Recipient", "Danh từ số nhiều 'articles' không cần mạo từ a/an."),
        ("We take a walk in the park after dinner.", "Chúng tôi đi dạo trong công viên sau bữa tối.", "S + V + O + Place + Time", "Cụm 'take a walk' là colocation phổ biến."),
        ("He washes his hands before eating meals.", "Anh ấy rửa tay trước khi ăn các bữa ăn.", "S + V + O + Time", "Sau 'before' là danh từ hoặc V-ing."),
        ("They visit their grandparents twice a month.", "Họ đến thăm ông bà hai lần một tháng.", "S + V + O + Frequency", "'twice a month' là cụm trạng từ chỉ tần suất."),
        ("I keep my desk organized and clean.", "Tôi giữ bàn làm việc của mình ngăn nắp và sạch sẽ.", "S + V + O + Adj", "Cấu trúc 'keep + O + Adj' (giữ cái gì ở trạng thái nào)."),
        ("She buys fresh vegetables at the local market.", "Cô ấy mua rau tươi tại chợ địa phương.", "S + V + O + Place", "Tính từ 'fresh' đứng trước danh từ 'vegetables'."),
        ("We watch news on television every evening.", "Chúng tôi xem tin tức trên truyền hình mỗi buổi tối.", "S + V + O + Medium + Time", "Dùng giới từ 'on' với television/radio."),
        ("He feeds his dog early in the morning.", "Anh ấy cho chó ăn vào sáng sớm.", "S + V + O + Time", "'early in the morning' diễn tả sáng sớm."),
        ("They attend an online meeting every Monday morning.", "Họ tham gia một cuộc họp trực tuyến vào mỗi sáng thứ Hai.", "S + V + O + Time", "'attend' không cần giới từ to."),
        ("I drink two liters of water every single day.", "Tôi uống hai lít nước mỗi ngày.", "S + V + O + Frequency", "Cụm 'every single day' nhấn mạnh tính liên tục."),
        ("She sends a status report to her manager at 5 PM.", "Cô ấy gửi báo cáo tiến độ cho quản lý lúc 5 giờ chiều.", "S + V + O + Recipient + Time", "Cấu trúc 'send something to someone'."),
        ("We lock all doors and windows before leaving home.", "Chúng tôi khóa tất cả cửa ra vào và cửa sổ trước khi rời nhà.", "S + V + O + Time", "Sau 'before' là V-ing 'leaving'.")
    ]),
    ("s1_02_wh", "Mẫu Câu Hỏi Wh- & Tra Cứu Thông Tin", "Wh- Questions & Inversion", "Hỏi thông tin tự nhiên với Wh-questions và cấu trúc đảo ngữ cơ bản.", "HelpCircle", "Beginner", [
        ("What time does the store open in the morning?", "Cửa hàng mở cửa lúc mấy giờ vào buổi sáng?", "What time + does + S + V + Time", "Dùng trợ động từ 'does' cho chủ ngữ số ít 'the store'."),
        ("Where can I find the nearest bus station?", "Tôi có thể tìm trạm xe buýt gần nhất ở đâu?", "Where + can + S + V + O", "Dùng 'can' hỏi về khả năng/địa điểm."),
        ("Why did you decide to change your career path?", "Tại sao bạn lại quyết định thay đổi con đường sự nghiệp?", "Why + did + S + V + O", "Dùng 'did' cho câu hỏi quá khứ."),
        ("How long does it take to travel to the airport?", "Mất bao lâu để di chuyển đến sân bay?", "How long + does it take + to V", "Cấu trúc 'How long does it take to do something'."),
        ("Who is responsible for managing this project?", "Ai là người chịu trách nhiệm quản lý dự án này?", "Who + be + responsible for + V-ing", "Cụm 'be responsible for + V-ing'."),
        ("Which option do you think is better for our team?", "Bạn nghĩ lựa chọn nào tốt hơn cho nhóm chúng ta?", "Which + O + do you think + is Adj", "Câu hỏi lồng 'do you think'."),
        ("When will the next training session begin?", "Khi nào buổi đào tạo tiếp theo sẽ bắt đầu?", "When + will + S + V", "Dùng 'will' hỏi về sự kiện tương lai."),
        ("How much does this service cost per month?", "Dịch vụ này có giá bao nhiêu tiền mỗi tháng?", "How much + does + S + cost + Time", "'cost' đóng vai trò là động từ chính."),
        ("What kind of music do you usually listen to?", "Bạn thường nghe thể loại nhạc nào?", "What kind of + N + do + S + V + Prep", "Giới từ 'to' đi kèm với 'listen' ở cuối câu."),
        ("How often do you go to the gym each week?", "Bạn đi tập gym bao nhiêu lần mỗi tuần?", "How often + do + S + V + Time", "'How often' hỏi về tần suất thực hiện hành động."),
        ("Where did you buy that beautiful leather jacket?", "Bạn đã mua chiếc áo khoác da đẹp đó ở đâu vậy?", "Where + did + S + V + O", "Động từ 'buy' giữ nguyên thể sau trợ động từ 'did'."),
        ("Why is the website loading so slowly right now?", "Tại sao trang web hiện tại lại tải chậm như vậy?", "Why + is + S + V-ing + Adv + Time", "Thì hiện tại tiếp diễn với 'is loading'."),
        ("What are the main requirements for this job position?", "Các yêu cầu chính cho vị trí công việc này là gì?", "What + are + the main requirements for + N", "Dùng 'are' vì 'requirements' là số nhiều."),
        ("How do you pronounce this English word correctly?", "Bạn phát âm từ tiếng Anh này một cách chính xác như thế nào?", "How + do + S + V + O + Adv", "'correctly' là trạng từ bổ nghĩa cho động từ 'pronounce'."),
        ("Who should I contact if I have questions?", "Tôi nên liên hệ với ai nếu tôi có thắc mắc?", "Who + should + S + V + Condition", "Mệnh đề điều kiện 'if I have questions'."),
        ("Which platform do you prefer for online meetings?", "Bạn thích nền tảng nào hơn cho các cuộc họp trực tuyến?", "Which + N + do + S + prefer + for N", "'prefer' diễn tả sự ưa thích lựa chọn."),
        ("What makes this product different from competitors?", "Điều gì làm cho sản phẩm này khác biệt so với đối thủ?", "What + makes + O + Adj + from N", "Cấu trúc 'make something different from'."),
        ("How can we improve our customer service quality?", "Làm thế nào chúng ta có thể cải thiện chất lượng dịch vụ khách hàng?", "How + can + S + V + O", "Dùng 'can' để tìm kiếm giải pháp."),
        ("When is the best time to visit this city?", "Thời điểm nào là tốt nhất để ghé thăm thành phố này?", "When + is + the best time to V", "Cấu trúc so sánh nhất 'the best time'."),
        ("Where do you see yourself in five years?", "Bạn thấy bản thân mình ở đâu trong năm năm tới?", "Where + do + S + see + Reflexive + Time", "Câu hỏi phỏng vấn kinh điển về định hướng tương lai."),
        ("Why did they cancel the flight this morning?", "Tại sao họ lại hủy chuyến bay sáng nay?", "Why + did + S + V + O + Time", "Dùng 'did' cho sự việc đã diễn ra trong quá khứ."),
        ("What happened during the meeting yesterday?", "Chuyện gì đã xảy ra trong suốt cuộc họp ngày hôm qua?", "What + happened + Prep + Time", "'What' đóng vai trò là chủ ngữ trực tiếp."),
        ("How many people attended the annual conference?", "Có bao nhiêu người đã tham dự hội nghị thường niên?", "How many + Ns + V + O", "'How many' luôn đi với danh từ đếm được số nhiều."),
        ("Which route is the fastest way to get there?", "Tuyến đường nào là cách nhanh nhất để đến đó?", "Which + N + is + the fastest way to V", "'the fastest' là cấp so sánh nhất."),
        ("What do you usually do in your free time?", "Bạn thường làm gì vào thời gian rảnh rỗi?", "What + do + S + Adv + V + Time", "Câu hỏi giao tiếp thường ngày quen thuộc.")
    ]),
    ("s1_03_requests", "Yêu Cầu & Xin Phép Lịch Sự", "Polite Requests & Permissions", "Nói tiếng Anh nhã nhặn, chuẩn mực với Could you, Would you mind, May I.", "MessageSquare", "Beginner", [
        ("Could you please send me the report by tomorrow?", "Bạn có thể vui lòng gửi cho tôi bản báo cáo trước ngày mai được không?", "Could you please + V + O + Time", "'Could' thể hiện sự lịch sự hơn 'Can'."),
        ("Would you mind opening the window for fresh air?", "Bạn có phiền mở cửa sổ cho thoáng khí được không?", "Would you mind + V-ing + O", "Sau 'Would you mind' luôn là V-ing."),
        ("May I have a glass of warm water, please?", "Tôi có thể xin một ly nước ấm được không?", "May I have + O, please", "'May I' dùng khi xin phép lịch sự."),
        ("Could you explain that technical term again?", "Bạn có thể giải thích lại thuật ngữ kỹ thuật đó được không?", "Could you + V + O + Adv", "'again' đặt cuối câu để yêu cầu lặp lại."),
        ("Would you please speak a little more slowly?", "Bạn có thể vui lòng nói chậm hơn một chút được không?", "Would you please + V + Adv", "'a little more slowly' là cụm trạng từ so sánh hơn."),
        ("Do you mind if I borrow your pen for a minute?", "Bạn có phiền nếu tôi mượn bút của bạn một phút không?", "Do you mind if + S + V", "Sau 'Do you mind if' là mệnh đề thì hiện tại đơn."),
        ("Could you give me a hand with this heavy box?", "Bạn có thể giúp tôi một tay với chiếc hộp nặng này không?", "Could you give me a hand with + N", "'give someone a hand' là thành ngữ chỉ việc giúp đỡ."),
        ("Would it be possible to reschedule our meeting?", "Liệu có thể đổi lịch cuộc họp của chúng ta được không?", "Would it be possible to + V", "Cách nói trang trọng để đề xuất thay đổi lịch trình."),
        ("May I leave the office a bit earlier today?", "Tôi có thể xin phép rời văn phòng sớm hơn một chút hôm nay được không?", "May I + V + Place + Time", "Dùng 'May I' khi xin phép cấp trên."),
        ("Could you please turn down the volume a bit?", "Bạn có thể vui lòng vặn nhỏ âm lượng lại một chút được không?", "Could you please turn down + O", "'turn down' là phrasal verb chỉ giảm âm lượng."),
        ("Would you mind repeating what you just said?", "Bạn có phiền nhắc lại điều bạn vừa nói không?", "Would you mind repeating + Clause", "'what you just said' là mệnh đề danh từ."),
        ("Can you hold the elevator for a second, please?", "Bạn có thể giữ thang máy giúp tôi một giây được không?", "Can you hold + O + Time", "Thêm 'please' cuối câu giúp tăng tính lịch sự."),
        ("Could I have your contact information for future reference?", "Tôi có thể xin thông tin liên hệ của bạn để tiện trao đổi sau này không?", "Could I have + O + Purpose", "'for future reference' là cụm từ trang trọng."),
        ("Would you be able to review this draft this afternoon?", "Bạn có thể xem qua bản nháp này vào chiều nay được không?", "Would you be able to + V + Time", "Cấu trúc trang trọng thay cho 'Can you'."),
        ("May I ask a question regarding this presentation?", "Tôi có thể hỏi một câu hỏi liên quan đến bài thuyết trình này được không?", "May I ask + O + regarding N", "'regarding' mang nghĩa liên quan đến."),
        ("Could you please double-check these numbers for me?", "Bạn có thể vui lòng kiểm tra lại những con số này giúp tôi không?", "Could you please double-check + O", "'double-check' nghĩa là kiểm tra lại lần hai cho chắc chắn."),
        ("Would you mind turning off the lights when you leave?", "Bạn có phiền tắt đèn khi bạn rời đi không?", "Would you mind turning off + O + Clause", "Mệnh đề thời gian 'when you leave'."),
        ("Could you let me know when the manager arrives?", "Bạn có thể báo cho tôi biết khi nào người quản lý đến không?", "Could you let me know + Clause", "'let someone know' nghĩa là thông báo cho ai."),
        ("May I sit here if nobody is occupying this seat?", "Tôi có thể ngồi đây nếu không có ai ngồi ghế này không?", "May I sit here + Condition", "Cách hỏi lịch sự ở nơi công cộng."),
        ("Would you mind sharing your notes from yesterday lecture?", "Bạn có phiền chia sẻ ghi chép từ bài giảng hôm qua không?", "Would you mind sharing + O", "'lecture' là bài giảng ở trường đại học."),
        ("Could you please guide me through this registration process?", "Bạn có thể vui lòng hướng dẫn tôi qua quy trình đăng ký này không?", "Could you please guide me through + N", "'guide someone through' nghĩa là hướng dẫn từng bước."),
        ("Would you be so kind as to forward that email to me?", "Bạn có thể vui lòng chuyển tiếp email đó cho tôi được không?", "Would you be so kind as to + V", "Cách yêu cầu cực kỳ trang trọng và lịch thiệp."),
        ("Could I trouble you to sign this document?", "Tôi có thể làm phiền bạn ký vào tài liệu này được không?", "Could I trouble you to + V", "Thành ngữ lịch sự khi nhờ vả ký giấy tờ."),
        ("May I have your attention for just two minutes?", "Xin mọi người vui lòng chú ý trong chỉ hai phút được không?", "May I have your attention + Time", "Dùng khi bắt đầu thông báo trước đám đông."),
        ("Could you please confirm your attendance by Friday?", "Bạn có thể vui lòng xác nhận sự tham gia của bạn trước thứ Sáu không?", "Could you please confirm + O + Time", "'by Friday' nghĩa là hạn chót vào thứ Sáu.")
    ]),
    ("s1_04_plans", "Kế Hoạch & Dự Định Tương Lai", "Plans, Intentions & Future", "Khung tư duy diễn tả dự định tương lai và suy nghĩ cá nhân.", "Calendar", "Beginner", [
        ("I am planning to travel to Japan this autumn.", "Tôi đang lên kế hoạch đi du lịch Nhật Bản vào mùa thu này.", "S + be planning to + V + Time", "Cấu trúc 'be planning to do something' chỉ kế hoạch cụ thể."),
        ("She is going to start her new job next Monday.", "Cô ấy sẽ bắt đầu công việc mới vào thứ Hai tới.", "S + be going to + V + Time", "'be going to' dùng cho kế hoạch đã được quyết định từ trước."),
        ("We intend to launch our new mobile application next quarter.", "Chúng tôi dự định ra mắt ứng dụng di động mới vào quý tới.", "S + intend to + V + Time", "'intend to' thể hiện ý định rõ ràng."),
        ("He is thinking about buying a new electric car.", "Anh ấy đang cân nhắc việc mua một chiếc xe ô tô điện mới.", "S + be thinking about + V-ing", "Sau 'think about' luôn là danh động từ V-ing."),
        ("They hope to expand their business to international markets.", "Họ hy vọng mở rộng việc kinh doanh ra thị trường quốc tế.", "S + hope to + V + O", "'hope to' thể hiện mong muốn và hy vọng tương lai."),
        ("I have decided to enroll in an advanced English course.", "Tôi đã quyết định đăng ký một khóa học tiếng Anh nâng cao.", "S + have decided to + V + O", "'decide to' kết hợp thì hiện tại hoàn thành."),
        ("She aims to achieve an IELTS score of 7.5 this year.", "Cô ấy đặt mục tiêu đạt điểm IELTS 7.5 trong năm nay.", "S + aim to + V + O + Time", "'aim to' chỉ mục tiêu cụ thể cần đạt được."),
        ("We are looking forward to meeting our new partners tomorrow.", "Chúng tôi rất mong đợi được gặp đối tác mới vào ngày mai.", "S + be looking forward to + V-ing", "Chú ý: Sau 'look forward to' luôn là V-ing."),
        ("He is preparing to take the university entrance examination.", "Anh ấy đang chuẩn bị thi kỳ thi tuyển sinh đại học.", "S + be preparing to + V + O", "'prepare to do something' chỉ hành động chuẩn bị."),
        ("They are scheduled to visit our office on Friday morning.", "Họ được lên lịch ghé thăm văn phòng chúng tôi vào sáng thứ Sáu.", "S + be scheduled to + V + Time", "Cấu trúc bị động chỉ lịch trình cố định."),
        ("I will make sure all tasks are completed on time.", "Tôi sẽ đảm bảo mọi nhiệm vụ được hoàn thành đúng hạn.", "S + will make sure + Clause", "'make sure' nghĩa là đảm bảo chắc chắn."),
        ("She promises to deliver the project before the deadline.", "Cô ấy hứa sẽ bàn giao dự án trước thời hạn chót.", "S + promise to + V + Time", "'promise to do something' thể hiện lời hứa."),
        ("We are bound to face challenges during the transition period.", "Chúng tôi chắc chắn sẽ gặp phải khó khăn trong giai đoạn chuyển đổi.", "S + be bound to + V", "'be bound to' chỉ sự việc chắc chắn sẽ xảy ra."),
        ("He is about to leave for his flight to Singapore.", "Anh ấy chuẩn bị đi ra sân bay cho chuyến bay đến Singapore.", "S + be about to + V", "'be about to' chỉ hành động sắp xảy ra ngay tức thì."),
        ("They are likely to accept our business proposal.", "Họ có nhiều khả năng sẽ chấp nhận đề xuất kinh doanh của chúng tôi.", "S + be likely to + V", "'be likely to' chỉ khả năng cao sẽ xảy ra."),
        ("I am determined to master English pronunciation this year.", "Tôi quyết tâm làm chủ phát âm tiếng Anh trong năm nay.", "S + be determined to + V", "'be determined to' thể hiện ý chí quyết tâm cao."),
        ("She wants to gain more hands-on experience in marketing.", "Cô ấy muốn tích lũy thêm kinh nghiệm thực tế trong ngành tiếp thị.", "S + want to + V + O", "'hands-on experience' nghĩa là kinh nghiệm thực chiến."),
        ("We plan on conducting a customer satisfaction survey soon.", "Chúng tôi dự định tiến hành khảo sát sự hài lòng của khách hàng sớm.", "S + plan on + V-ing + Time", "'plan on' đi kèm với danh động từ V-ing."),
        ("He expects to receive a job offer by next week.", "Anh ấy kỳ vọng sẽ nhận được lời mời làm việc trước tuần tới.", "S + expect to + V + Time", "'expect to' diễn tả sự kỳ vọng."),
        ("They aspire to become the leading technology firm in Asia.", "Họ khao khát trở thành công ty công nghệ hàng đầu tại châu Á.", "S + aspire to + V + O", "'aspire to' thể hiện khát vọng lớn."),
        ("I am set to graduate from university next summer.", "Tôi dự kiến sẽ tốt nghiệp đại học vào mùa hè năm sau.", "S + be set to + V + Time", "'be set to' chỉ lịch trình đã được định sẵn."),
        ("She hopes that her application will be approved soon.", "Cô ấy hy vọng rằng đơn xin của mình sẽ sớm được phê duyệt.", "S + hope that + Clause", "'hope that' đi với mệnh đề tương lai."),
        ("We are ready to start the implementation phase immediately.", "Chúng tôi đã sẵn sàng bắt đầu giai đoạn triển khai ngay lập tức.", "S + be ready to + V + Adv", "'be ready to do something' chỉ sự sẵn sàng."),
        ("He intends on pursuing a master degree in artificial intelligence.", "Anh ấy có ý định theo học bằng thạc sĩ về trí tuệ nhân tạo.", "S + intend on + V-ing", "'pursue a degree' nghĩa là theo đuổi học vị."),
        ("They will probably announce the new product release next month.", "Họ có lẽ sẽ công bố đợt ra mắt sản phẩm mới vào tháng sau.", "S + will probably + V + Time", "'probably' bổ nghĩa mức độ khả năng cho 'will'.")
    ]),
    ("s1_05_conditionals", "Câu Điều Kiện (Type 0, 1 & 2)", "Conditionals & Logic", "Diễn đạt nguyên nhân - kết quả và các giả định logic trong giao tiếp.", "GitBranch", "Intermediate", [
        ("If you heat water to one hundred degrees, it boils.", "Nếu bạn đun nước đến 100 độ C, nó sẽ sôi.", "If + Present Simple, Present Simple", "Điều kiện loại 0 diễn tả sự thật hiển nhiên hoặc chân lý."),
        ("If it rains tomorrow, we will stay at home.", "Nếu ngày mai trời mưa, chúng tôi sẽ ở nhà.", "If + Present Simple, will + V", "Điều kiện loại 1 diễn tả khả năng có thể xảy ra ở hiện tại hoặc tương lai."),
        ("If I have free time tonight, I will call you.", "Nếu tối nay tôi rảnh rỗi, tôi sẽ gọi điện cho bạn.", "If + Present Simple, will + V", "Thì hiện tại đơn trong mệnh đề if chỉ điều kiện tương lai."),
        ("If she studies hard, she will pass the examination.", "Nếu cô ấy học tập chăm chỉ, cô ấy sẽ đỗ kỳ thi.", "If + Present Simple, will + V", "'studies' chia theo ngôi thứ ba số ít."),
        ("If you do not hurry, you will miss the train.", "Nếu bạn không khẩn trương, bạn sẽ bị lỡ chuyến tàu.", "If + Negative, will + V", "'miss the train' nghĩa là lỡ tàu."),
        ("If I were you, I would accept that job offer.", "Nếu tôi là bạn, tôi sẽ nhận lời mời làm việc đó.", "If I were + you, I would + V", "Điều kiện loại 2 giả định điều không có thật ở hiện tại, dùng 'were' cho mọi ngôi."),
        ("If he had more money, he would buy a new house.", "Nếu anh ấy có nhiều tiền hơn, anh ấy sẽ mua một căn nhà mới.", "If + Past Simple, would + V", "Điều kiện loại 2 diễn tả ước muốn trái với thực tế."),
        ("If we work together, we can achieve our quarterly targets.", "Nếu chúng ta cùng nhau làm việc, chúng ta có thể đạt được các mục tiêu quý.", "If + Present Simple, can + V", "Dùng 'can' trong mệnh đề chính để chỉ khả năng."),
        ("Unless you practice speaking regularly, you will not improve.", "Trừ khi bạn luyện nói thường xuyên, nếu không bạn sẽ không tiến bộ.", "Unless + Clause, will not + V", "'Unless' tương đương với 'If not'."),
        ("If you need any assistance, please do not hesitate to ask.", "Nếu bạn cần bất kỳ sự hỗ trợ nào, xin đừng ngần ngại hỏi.", "If + Clause, Imperative", "Mệnh đề chính dùng câu mệnh lệnh lịch sự."),
        ("If the traffic is heavy, I might arrive slightly late.", "Nếu giao thông bị ùn tắc, tôi có thể sẽ đến muộn một chút.", "If + Clause, might + V", "'might' diễn tả khả năng không chắc chắn 100%."),
        ("If I knew the answer, I would tell you immediately.", "Nếu tôi biết câu trả lời, tôi sẽ nói cho bạn ngay lập tức.", "If + Past Simple, would + V", "Giả định trái với hiện tại (thực tế là không biết)."),
        ("Provided that you finish the work, you may leave early.", "Với điều kiện là bạn hoàn thành công việc, bạn có thể về sớm.", "Provided that + Clause, may + V", "'Provided that' đồng nghĩa với 'If' nhưng trang trọng hơn."),
        ("As long as you believe in yourself, you can succeed.", "Miễn là bạn tin vào chính mình, bạn có thể thành công.", "As long as + Clause, can + V", "'As long as' nghĩa là miễn là."),
        ("If we do not reduce costs, we will lose profitability.", "Nếu chúng ta không cắt giảm chi phí, chúng ta sẽ mất khả năng sinh lời.", "If + Negative, will + V", "'profitability' là khả năng sinh lợi nhuận."),
        ("If she were here right now, she would know what to do.", "Nếu cô ấy ở đây lúc này, cô ấy sẽ biết phải làm gì.", "If + were, would + V", "Giả định trái thực tế hiện tại."),
        ("In case it gets cold tonight, remember to bring a jacket.", "Phòng khi trời trở lạnh tối nay, hãy nhớ mang theo áo khoác.", "In case + Clause, Imperative", "'In case' diễn tả sự chuẩn bị đề phòng."),
        ("If you follow the instructions, you will avoid common mistakes.", "Nếu bạn làm theo hướng dẫn, bạn sẽ tránh được các lỗi phổ biến.", "If + Clause, will + V", "'avoid mistakes' là tránh sai lầm."),
        ("Had I known about the issue, I would have warned you.", "Nếu tôi biết về vấn đề đó, tôi đã cảnh báo bạn rồi.", "Had + S + V3, would have + V3", "Đảo ngữ điều kiện loại 3 diễn tả sự việc đã qua trong quá khứ."),
        ("If you feel tired, you should take a short break.", "Nếu bạn cảm thấy mệt mỏi, bạn nên nghỉ ngơi một chút.", "If + Clause, should + V", "Dùng 'should' đưa ra lời khuyên."),
        ("If the server goes down, the backup system activates automatically.", "Nếu máy chủ gặp sự cố, hệ thống sao lưu sẽ tự động kích hoạt.", "If + Present Simple, Present Simple", "Quy trình kỹ thuật tự động hóa (Type 0)."),
        ("Should you require further information, please contact our support team.", "Nếu bạn cần thêm thông tin, vui lòng liên hệ đội ngũ hỗ trợ của chúng tôi.", "Should + S + V, Imperative", "Đảo ngữ điều kiện loại 1 cực kỳ trang trọng trong văn bản."),
        ("If we invest in automation now, we will save time later.", "Nếu chúng ta đầu tư vào tự động hóa bây giờ, chúng ta sẽ tiết kiệm thời gian sau này.", "If + Present Simple, will + V", "'invest in' luôn đi kèm giới từ 'in'."),
        ("Unless the weather improves, the outdoor event will be postponed.", "Trừ phi thời tiết cải thiện, sự kiện ngoài trời sẽ bị hoãn lại.", "Unless + Clause, will be V3", "'postponed' là bị hoãn lại.")
    ]),
    ("s1_06_modals", "Động Từ Khuyết Thiếu & Khuyên Bảo", "Modal Verbs of Advice & Obligation", "Dùng must, should, have to, ought to, may, can chuẩn xác.", "Shield", "Beginner", [
        ("You should back up your important files regularly.", "Bạn nên sao lưu các tệp tin quan trọng của mình thường xuyên.", "S + should + V + O + Adv", "'should' dùng để đưa ra lời khuyên hữu ích."),
        ("Employees must wear security badges at all times.", "Nhân viên bắt buộc phải đeo thẻ an ninh mọi lúc.", "S + must + V + O + Time", "'must' chỉ quy định bắt buộc mang tính pháp lý."),
        ("You do not have to work overtime on weekends.", "Bạn không cần phải làm thêm giờ vào cuối tuần.", "S + do not have to + V + Time", "'not have to' chỉ sự không cần thiết (khác với 'must not')."),
        ("We ought to respect different cultural viewpoints and backgrounds.", "Chúng ta nên tôn trọng các quan điểm và nền tảng văn hóa khác nhau.", "S + ought to + V + O", "'ought to' tương đương với 'should' nhưng mang tính đạo đức."),
        ("You had better save your progress before updating software.", "Tốt hơn hết bạn nên lưu lại tiến trình trước khi cập nhật phần mềm.", "S + had better + V + O", "'had better' là lời khuyên mạnh mẽ cảnh báo hậu quả."),
        ("You must not share your master password with anyone.", "Bạn tuyệt đối không được chia sẻ mật khẩu chính với bất kỳ ai.", "S + must not + V + O", "'must not' chỉ sự cấm đoán tuyệt đối."),
        ("We should consider all possible alternatives before deciding.", "Chúng ta nên cân nhắc mọi phương án thay thế khả thi trước khi quyết định.", "S + should + V + O + Time", "'alternatives' là các phương án lựa chọn khác."),
        ("You can definitely achieve your language learning goals.", "Bạn chắc chắn có thể đạt được các mục tiêu học ngoại ngữ của mình.", "S + can definitely + V + O", "'definitely' nhấn mạnh sự chắc chắn."),
        ("She may join our project team next month.", "Cô ấy có thể sẽ gia nhập nhóm dự án của chúng ta vào tháng tới.", "S + may + V + O + Time", "'may' chỉ khả năng xảy ra khoảng 50%."),
        ("You need to verify your email address to continue.", "Bạn cần phải xác minh địa chỉ email của mình để tiếp tục.", "S + need to + V + O + Purpose", "'verify' nghĩa là xác minh tính đúng đắn."),
        ("We could explore alternative solutions if this approach fails.", "Chúng ta có thể khám phá các giải pháp thay thế nếu cách này thất bại.", "S + could + V + O + Condition", "'could' gợi ý một giải pháp khả dĩ."),
        ("You ought not to skip basic warm-up exercises.", "Bạn không nên bỏ qua các bài tập khởi động cơ bản.", "S + ought not to + V + O", "Dạng phủ định của 'ought to'."),
        ("Drivers must obey speed limits in school zones.", "Người lái xe phải tuân thủ giới hạn tốc độ trong khu vực trường học.", "S + must obey + O + Place", "'obey limits' nghĩa là tuân thủ giới hạn."),
        ("You should never compromise on software code quality.", "Bạn không bao giờ nên thỏa hiệp về chất lượng mã nguồn phần mềm.", "S + should never + V + on N", "'compromise on' là thỏa hiệp, hạ thấp tiêu chuẩn."),
        ("We have to submit our tax declarations before April.", "Chúng tôi phải nộp tờ khai thuế trước tháng Tư.", "S + have to + V + O + Time", "'have to' diễn tả nghĩa vụ khách quan do ngoại cảnh."),
        ("You might want to double-check those financial figures.", "Có lẽ bạn sẽ muốn kiểm tra lại những con số tài chính đó.", "S + might want to + V + O", "Cách nói giảm nói tránh lịch sự khi muốn ai kiểm tra lại."),
        ("Users must agree to the terms and conditions.", "Người dùng phải đồng ý với các điều khoản và điều kiện.", "S + must agree to + O", "'terms and conditions' là điều khoản sử dụng."),
        ("You should take notes during the technical seminar.", "Bạn nên ghi chép trong suốt buổi hội thảo chuyên môn.", "S + should take notes + Time", "'seminar' là hội thảo học thuật/chuyên môn."),
        ("We can easily resolve this issue with proper tools.", "Chúng ta có thể dễ dàng giải quyết vấn đề này với công cụ phù hợp.", "S + can easily + V + O + Means", "'easily' là trạng từ bổ nghĩa cho động từ 'resolve'."),
        ("You must ensure data consistency across all servers.", "Bạn phải đảm bảo tính nhất quán của dữ liệu trên mọi máy chủ.", "S + must ensure + O + Place", "'data consistency' là tính nhất quán dữ liệu."),
        ("They ought to inform customers about scheduled maintenance downtime.", "Họ nên thông báo cho khách hàng về thời gian bảo trì định kỳ.", "S + ought to inform + O + about N", "'maintenance downtime' là thời gian dừng hệ thống bảo trì."),
        ("You do not need to memorize every single formula.", "Bạn không cần phải học thuộc lòng từng công thức đơn lẻ.", "S + do not need to + V + O", "'memorize' nghĩa là ghi nhớ máy móc."),
        ("We must focus our resources on high-priority objectives.", "Chúng ta phải tập trung nguồn lực vào các mục tiêu ưu tiên cao.", "S + must focus + O + on N", "'high-priority' là ưu tiên hàng đầu."),
        ("You should always maintain a healthy work-life balance.", "Bạn nên luôn luôn duy trì sự cân bằng lành mạnh giữa công việc và cuộc sống.", "S + should always maintain + O", "'work-life balance' là sự cân bằng công việc - đời sống.")
    ]),
    ("s1_07_comparisons", "So Sánh & Cấp Độ Đánh Giá", "Comparisons & Degrees", "So sánh bằng, hơn, nhất để đánh giá và lựa chọn giải pháp.", "TrendingUp", "Beginner", [
        ("This new laptop is significantly faster than my old one.", "Chiếc máy tính xách tay mới này nhanh hơn đáng kể so với chiếc cũ của tôi.", "S + is significantly + Adj-er than + N", "'significantly' là trạng từ nhấn mạnh mức độ chênh lệch lớn."),
        ("Our current solution is as efficient as the leading competitor.", "Giải pháp hiện tại của chúng ta hiệu quả ngang bằng đối thủ dẫn đầu.", "S + is as + Adj + as + N", "Cấu trúc so sánh bằng 'as + Adj + as'."),
        ("Python is generally easier to learn than C plus plus.", "Python nhìn chung dễ học hơn so với C++.", "S + is easier to learn than + N", "'easier' là dạng so sánh hơn của tính từ ngắn 'easy'."),
        ("This is the most reliable database engine available today.", "Đây là hệ quản trị cơ sở dữ liệu đáng tin cậy nhất hiện có ngày nay.", "S + is the most + Adj + N", "Cấu trúc so sánh nhất của tính từ dài 'reliable'."),
        ("The second option is far more expensive than expected.", "Lựa chọn thứ hai đắt hơn nhiều so với dự kiến.", "S + is far more + Adj than + Clause", "'far more' dùng để nhấn mạnh sự vượt trội."),
        ("Our team delivered the product twice as fast as last year.", "Nhóm chúng tôi đã bàn giao sản phẩm nhanh gấp đôi so với năm ngoái.", "S + V + twice as + Adv + as + Time", "Cấu trúc so sánh bội số 'twice as ... as'."),
        ("No other candidate is better qualified for this senior position.", "Không có ứng viên nào khác có đủ năng lực tốt hơn cho vị trí cấp cao này.", "No other + N + is better qualified", "'better qualified' là đủ tiêu chuẩn tốt hơn."),
        ("The closer we get to the deadline, the more focused we become.", "Càng tiến gần đến thời hạn chót, chúng ta càng trở nên tập trung hơn.", "The + Comparative, the + Comparative", "Cấu trúc so sánh kép 'Càng... thì càng...'."),
        ("This algorithm is slightly more complex but remarkably faster.", "Thuật toán này phức tạp hơn một chút nhưng nhanh hơn rõ rệt.", "S + is slightly more Adj but Adv-er", "'slightly' (một chút), 'remarkably' (đáng kể)."),
        ("Today temperature is much colder than yesterday.", "Nhiệt độ hôm nay lạnh hơn nhiều so với ngày hôm qua.", "S + is much + Adj-er than + Time", "'much' dùng để nhấn mạnh so sánh hơn."),
        ("The user interface is becoming simpler and more intuitive.", "Giao diện người dùng đang ngày càng trở nên đơn giản và trực quan hơn.", "S + is becoming + Comparative and Comparative", "'intuitive' nghĩa là trực quan, dễ dùng."),
        ("That was the least complicated task in the entire sprint.", "Đó là nhiệm vụ ít phức tạp nhất trong toàn bộ giai đoạn sprint.", "S + was the least + Adj + N", "'the least' là so sánh kém nhất."),
        ("Automated tests are considerably safer than manual verification.", "Kiểm thử tự động an toàn hơn đáng kể so với việc xác minh thủ công.", "S + are considerably + Adj-er than + N", "'considerably' nghĩa là rất nhiều, đáng kể."),
        ("Her English pronunciation is getting better and better every day.", "Phát âm tiếng Anh của cô ấy đang ngày càng tốt hơn mỗi ngày.", "S + is getting better and better + Time", "'better and better' diễn tả sự tiến bộ liên tục."),
        ("This is by far the best framework for building web apps.", "Đây chắc chắn là framework tốt nhất từ trước đến nay để xây dựng ứng dụng web.", "S + is by far the best + N", "'by far' dùng để nhấn mạnh cấp so sánh nhất."),
        ("The battery life lasts three times longer on this model.", "Thời lượng pin kéo dài gấp ba lần trên mẫu máy này.", "S + lasts three times longer + Place", "So sánh bội số 'three times longer'."),
        ("Nothing is more valuable than practical real-world experience.", "Không có gì quý giá hơn kinh nghiệm thực tế ngoài đời thực.", "Nothing is more + Adj than + N", "'real-world experience' là kinh nghiệm thực chiến."),
        ("The earlier you submit the proposal, the sooner we can review it.", "Bạn nộp đề xuất càng sớm thì chúng tôi càng có thể xem xét sớm.", "The earlier + Clause, the sooner + Clause", "Cấu trúc so sánh lũy tiến 'The earlier... the sooner...'."),
        ("This code is not as clean as it should be.", "Đoạn mã này không được sạch sẽ như nó cần phải có.", "S + is not as + Adj + as + Clause", "So sánh không bằng 'not as ... as'."),
        ("He is the most experienced engineer on our development team.", "Anh ấy là kỹ sư giàu kinh nghiệm nhất trong nhóm phát triển của chúng tôi.", "S + is the most experienced + N", "'experienced' nghĩa là dày dạn kinh nghiệm."),
        ("Electric vehicles produce significantly fewer carbon emissions than gasoline cars.", "Xe điện thải ra ít khí thải carbon hơn đáng kể so với xe chạy xăng.", "S + produce fewer + N + than + N", "'fewer' dùng với danh từ đếm được số nhiều 'emissions'."),
        ("The new version consumes much less battery power.", "Phiên bản mới tiêu thụ ít năng lượng pin hơn nhiều.", "S + consumes much less + N", "'less' dùng với danh từ không đếm được 'power'."),
        ("Public transportation is far cheaper than driving private cars.", "Phương tiện giao thông công cộng rẻ hơn nhiều so với việc lái xe cá nhân.", "S + is far cheaper than + V-ing", "'far cheaper' nghĩa là rẻ hơn rất nhiều."),
        ("This bug is the most critical issue in our backlog.", "Lỗi này là vấn đề nghiêm trọng nhất trong danh sách tồn đọng của chúng tôi.", "S + is the most critical issue", "'critical issue' là vấn đề cấp bách, nghiêm trọng.")
    ]),
    ("s1_08_emotions", "Cảm Xúc & Trạng Thái Cá Nhân", "Emotions, Feelings & Reactions", "Bộc lộ cảm nghĩ, sự quan tâm và thái độ một cách tinh tế.", "Smile", "Beginner", [
        ("I am really excited about our upcoming project launch.", "Tôi thực sự rất hào hứng về đợt ra mắt dự án sắp tới của chúng ta.", "S + be excited about + N", "'excited about' đi với danh từ chỉ sự kiện."),
        ("She feels confident about her public speaking presentation skills.", "Cô ấy cảm thấy tự tin về kỹ năng thuyết trình trước đám đông của mình.", "S + feel confident about + N", "'confident about' nghĩa là tự tin về điều gì."),
        ("We are extremely proud of our team remarkable achievement.", "Chúng tôi vô cùng tự hào về thành tích phi thường của nhóm mình.", "S + be proud of + N", "'proud of' luôn đi kèm giới từ 'of'."),
        ("He was deeply disappointed with the final test results.", "Anh ấy đã rất thất vọng với kết quả kiểm tra cuối cùng.", "S + be disappointed with + N", "'disappointed with' nghĩa là thất vọng với cái gì."),
        ("They are passionate about developing artificial intelligence solutions.", "Họ rất đam mê phát triển các giải pháp trí tuệ nhân tạo.", "S + be passionate about + V-ing", "'passionate about' thể hiện niềm đam mê sâu sắc."),
        ("I feel overwhelmed by the sheer volume of incoming tasks.", "Tôi cảm thấy bị quá tải bởi khối lượng công việc dồn dập đổ về.", "S + feel overwhelmed by + N", "'overwhelmed by' nghĩa là bị choáng ngợp/quá tải."),
        ("She was surprised to discover how easy the system was.", "Cô ấy đã rất ngạc nhiên khi khám phá ra hệ thống đó dễ sử dụng thế nào.", "S + be surprised to + V", "'surprised to do something'."),
        ("We are grateful for all the support we received.", "Chúng tôi vô cùng biết ơn tất cả sự hỗ trợ mà chúng tôi đã nhận được.", "S + be grateful for + N", "'grateful for' nghĩa là biết ơn về điều gì."),
        ("He is very interested in learning modern cloud architecture.", "Anh ấy rất hứng thú với việc học kiến trúc đám mây hiện đại.", "S + be interested in + V-ing", "'interested in' luôn đi cùng V-ing."),
        ("They felt relieved after successfully deploying the hotfix patch.", "Họ cảm thấy nhẹ nhõm sau khi triển khai thành công bản vá lỗi khẩn cấp.", "S + feel relieved after + V-ing", "'relieved' nghĩa là trút được gánh nặng, an tâm."),
        ("I am curious to see how users interact with features.", "Tôi rất tò mò muốn xem người dùng tương tác với các tính năng như thế nào.", "S + be curious to + V", "'curious to see' nghĩa là tò mò muốn thấy."),
        ("She got nervous before stepping onto the conference stage.", "Cô ấy đã hồi hộp trước khi bước lên sân khấu hội nghị.", "S + get nervous before + V-ing", "'nervous' nghĩa là lo lắng, bồn chồn."),
        ("We are completely satisfied with the product performance and stability.", "Chúng tôi hoàn toàn hài lòng với hiệu năng và độ ổn định của sản phẩm.", "S + be satisfied with + N", "'satisfied with' nghĩa là thỏa mãn, hài lòng."),
        ("He was confused by the conflicting instructions in the manual.", "Anh ấy đã bị bối rối bởi các chỉ dẫn mâu thuẫn trong sách hướng dẫn.", "S + be confused by + N", "'confused by' nghĩa là bị làm cho khó hiểu."),
        ("They are optimistic about the future growth of our company.", "Họ rất lạc quan về sự tăng trưởng tương lai của công ty chúng ta.", "S + be optimistic about + N", "'optimistic about' nghĩa là lạc quan về."),
        ("I feel inspired whenever I attend tech community meetups.", "Tôi cảm thấy tràn đầy cảm hứng mỗi khi tham dự các buổi gặp mặt cộng đồng công nghệ.", "S + feel inspired + Clause", "'inspired' nghĩa là được truyền cảm hứng."),
        ("She was hesitant to make such a major architectural change.", "Cô ấy đã ngập ngừng khi đưa ra một thay đổi kiến trúc lớn như vậy.", "S + be hesitant to + V", "'hesitant to do something' là do dự."),
        ("We were thrilled to win the first prize in hackathon.", "Chúng tôi đã vô cùng phấn khích khi giành giải nhất trong cuộc thi hackathon.", "S + be thrilled to + V", "'thrilled to do something' là vui sướng tột độ."),
        ("He feels exhausted after working continuously for twelve hours.", "Anh ấy cảm thấy kiệt sức sau khi làm việc liên tục suốt 12 tiếng.", "S + feel exhausted after + V-ing", "'exhausted' nghĩa là cạn kiệt sức lực."),
        ("They were impressed by the speed of our customer support.", "Họ đã rất ấn tượng trước tốc độ hỗ trợ khách hàng của chúng tôi.", "S + be impressed by + N", "'impressed by' nghĩa là bị ấn tượng bởi."),
        ("I am uncomfortable speaking in front of very large audiences.", "Tôi cảm thấy không thoải mái khi nói trước những khán phòng quá đông người.", "S + be uncomfortable + V-ing", "'uncomfortable' nghĩa là ngượng ngùng, không thoải mái."),
        ("She is enthusiastic about organizing our annual developer gathering.", "Cô ấy rất nhiệt huyết trong việc tổ chức buổi tụ họp lập trình viên thường niên.", "S + be enthusiastic about + V-ing", "'enthusiastic about' nghĩa là nhiệt tình, say mê."),
        ("We are cautious about adopting untested experimental frameworks.", "Chúng tôi rất thận trọng trong việc áp dụng các framework thử nghiệm chưa được kiểm chứng.", "S + be cautious about + V-ing", "'cautious about' nghĩa là cẩn trọng."),
        ("He was embarrassed when his phone rang during the silent ceremony.", "Anh ấy đã rất ngượng ngùng khi điện thoại reo vang trong buổi lễ trang nghiêm.", "S + was embarrassed when + Clause", "'embarrassed' là xấu hổ, ngượng ngùng.")
    ])
]

# Write Stage 1
for t_id, title_vi, title_en, desc, icon, level, raw in topics_raw:
    pass

print(f"Loaded {len(topics_raw)} topics for stage 1")
